=== dtune/feeling/settings/rateKey/RateKey-definition.dtd
<!ELEMENT Constraint EMPTY >
<!ATTLIST Constraint condition CDATA #REQUIRED >
<!ATTLIST Constraint keys CDATA #REQUIRED >
<!ATTLIST Constraint desc CDATA #IMPLIED >

<!ELEMENT Constraints ( Constraint+ ) >

<!ELEMENT RateKey ( items | rule )* >
<!ATTLIST RateKey displayOrder NMTOKEN #REQUIRED >
<!ATTLIST RateKey initValue NMTOKEN #IMPLIED >
<!ATTLIST RateKey label CDATA #REQUIRED >
<!ATTLIST RateKey name NMTOKEN #REQUIRED >
<!ATTLIST RateKey required NMTOKEN #IMPLIED >
<!ATTLIST RateKey selectedIndex NMTOKEN #IMPLIED >
<!ATTLIST RateKey type (text | radio | combo) #REQUIRED >

<!ELEMENT RateKey-definition ( Constraints*, RateKeys ) >

<!ELEMENT RateKeys ( RateKey+ ) >

<!ELEMENT item EMPTY >
<!ATTLIST item label CDATA #REQUIRED >
<!ATTLIST item value NMTOKEN #REQUIRED >

<!ELEMENT items ( item+ ) >

<!ELEMENT rule EMPTY >
<!ATTLIST rule max NMTOKEN #REQUIRED >
<!ATTLIST rule min NMTOKEN #REQUIRED >
<!ATTLIST rule specialValues CDATA #IMPLIED >
<!ATTLIST rule step NMTOKEN #IMPLIED >
<!ATTLIST rule validateDate ( true | false ) #IMPLIED >

=== dtune/feeling/settings/rateKey/dividend.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
  	<!-- レートキーのUI属性 -->
 	<RateKeys>
 		<RateKey name="policyCode" label="主契約コード" type="combo"
			displayOrder="72" selectedIndex="0">
			<items>
				<item label="004/005" value="004"/>
				<item label="008" value="008"/>
				<item label="009" value="009"/>
				<item label="011" value="011"/>
				<item label="013" value="013"/>
				<item label="017" value="017"/>
				<item label="042" value="042"/>
			</items>
		</RateKey>
		<RateKey name="policyContractDate" label="主契約契約日" type="text"
			required="true" initValue="20100331" displayOrder="73">
			<rule min="19600000" max="21001231" validateDate="true"/>
		</RateKey>
		<RateKey name="policyKaisu" label="主契約払込回数" type="combo" required="true"
			displayOrder="74" selectedIndex="0">
			<items>
				<item label="一時払" value="1" />
				<item label="年払" value="2" />
				<item label="半年払" value="3" />
				<item label="月払" value="4" />
			</items>
		</RateKey>
		<RateKey name="contractorState" label="契約現況" type="radio"
			required="true" displayOrder="75" selectedIndex="1">
			<items>
				<item label="消滅" value="0"/>
				<item label="存在" value="1"/>
			</items>
		</RateKey>
		<RateKey name="changeState" label="異動状態" type="combo"
			displayOrder="77" selectedIndex="2">
			<items>
				<item label="解約、解除等ペナルティ" value="0"/>
				<item label="減額" value="1"/>
				<item label="-" value="2"/>
			</items>
		</RateKey>
		<RateKey name="divEndDate" label="配当基準日" type="text"
			required="true" initValue="20110331" displayOrder="79">
			<rule min="19600000" max="21001231" validateDate="true"/>
		</RateKey>
		<RateKey name="SA_lastyear" label="前年度基本S" type="text" required="true"
			displayOrder="80" initValue="10000">
			<rule min="0" max="999999999" step="1" />
		</RateKey>
		<RateKey name="Dt_lastyear" label="前年度未割当残高" type="text"
			required="true" initValue="0" displayOrder="81">
			<rule min="-100000000" max="100000000" step="1"/>
		</RateKey>
		<RateKey name="Dt_thisyear" label="当年度未割当残高" type="text"
			required="true" initValue="0" displayOrder="82">
			<rule min="-100000000" max="100000000" step="1"/>
		</RateKey>
		<RateKey name="payState" label="分配後保険料入金状態" type="radio"
			required="true" displayOrder="83" selectedIndex="1">
			<items>
				<item label="なし" value="0"/>
				<item label="あり" value="1"/>
			</items>
		</RateKey>
        <RateKey name="oldAnnuityBuyDate" label="旧年金買増年月日" type="text" displayOrder="84">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>
        <RateKey name="newAnnuityBuyDate" label="最新年金買増年月" type="text" displayOrder="85">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>
        <RateKey name="effectBeginDate" label="効力発生日" type="text" displayOrder="87">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>
		<RateKey name="DividendValueLastYear" label="前年度積立配当金" type="text"
			required="true" initValue="0" displayOrder="88">
			<rule min="-100000000" max="100000000" step="1"/>
		</RateKey>
        <RateKey name="SA_nashu" label="減額保険金額" type="text"
			required="true" displayOrder="89" initValue="0">
			<rule min="0" max="100000000" step="1"/>
        </RateKey>
		<RateKey name="bonusDiv" label="ボーナス併用払" type="radio"
			required="true" displayOrder="93" selectedIndex="0">
			<items>
				<item label="なし" value="0"/>
				<item label="あり" value="1"/>
			</items>
		</RateKey>
		<RateKey name="psi" label="ボーナス倍数" type="combo"
		required="true" displayOrder="94">
			<items>
				<item label="3" value="3"/>
				<item label="5" value="5"/>
				<item label="7" value="7"/>
			</items>
		</RateKey>
		<RateKey name="bonus_month" label="ボーナス月" type="combo"
			required="true" displayOrder="95">
			<items>
				<item label="1月/7月" value="1"/>
				<item label="6月/12月" value="2"/>
				<item label="7月/12月" value="3"/>
			</items>
			<rule min="1" max="3" step="1"/>
		</RateKey>
		<RateKey name="keisanPtn" label="計算対象" type="combo"
			required="true" displayOrder="96">
			<items>
				<item label="未割当配当金残高" value="1"/>
				<item label="未割当分配額" value="2"/>
				<item label="割当済み分配額" value="3"/>
				<item label="積立配当金" value="4"/>
				<item label="アセットシェア" value="5"/>
			</items>
			<rule min="1" max="3" step="1"/>
		</RateKey>
    </RateKeys>
</RateKey-definition>

=== dtune/feeling/settings/rateKey/931.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
	<!-- レートキーの制御関係 -->
	<Constraints>
		<Constraint keys="n,m" condition="(m&lt;99&amp;&amp;n>=m)||(m==99)"
			desc="保険期間は払込期間より大きいで入力ください。" />
		<Constraint keys="kaisu,m"
			condition="(kaisu==1&amp;&amp;m==0)||(kaisu&gt;1&amp;&amp;m&gt;0)"
			desc="一時払いの場合、払込期間は0となければならない;分割払の場合、払込期間は0以上で入力ください。" />
	</Constraints>

	<!-- レートキーのUI属性 -->
	<RateKeys>
		<RateKey name="sex" label="性別" type="radio" required="true"
			displayOrder="3" selectedIndex="0">
			<items>
				<item label="男性" value="0" />
				<item label="女性" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="n" label="保険期間" type="text" required="true"
			initValue="10" displayOrder="4">
			<!-- 期間・年齢範囲チェックは商品毎に異なるので、レートキーのルール定義は直さないといけない -->
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="x" label="被年令" type="text" required="true"
			initValue="30" displayOrder="5">
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="kaisu" label="払込回数" type="combo" required="true"
			displayOrder="7" selectedIndex="0">
			<items>
				<item label="一時払" value="1" />
				<item label="年払" value="2" />
				<item label="半年払" value="3" />
				<item label="月払" value="4" />
			</items>
			<rule min="1" max="1" step="1" />
		</RateKey>
		<RateKey name="t" label="経過年" type="text" required="true"
			displayOrder="10">
			<rule min="0" max="90" step="1" />
		</RateKey>
		<RateKey name="f" label="経過月" type="text" required="true"
			displayOrder="11">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="t1" label="払込年" type="text" required="true"
			displayOrder="12">
			<rule min="0" max="90" step="1" />
		</RateKey>
		<RateKey name="f1" label="払込月" type="text" required="true"
			displayOrder="13">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="state" label="契約状態" type="combo" required="true"
			displayOrder="8" selectedIndex="1">
			<items>
				<item label="-" value="0" />
				<item label="保険料払込期間中" value="1" />
				<item label="保険料払込期間終了後" value="2" />
				<item label="払込免除" value="6" />
			</items>
			<rule min="0" max="6" step="1" />
		</RateKey>
		<RateKey name="sptate" label="S/P建" type="radio" required="true"
			displayOrder="10" selectedIndex="0">
			<items>
				<item label="S建" value="0" />
				<item label="P建" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="SA" label="基本S" type="text" required="true"
			displayOrder="16" initValue="10000">
			<rule min="0" max="999999999" step="1" />
		</RateKey>
		<RateKey name="contractDate" label="契約日" type="text"
			initValue="20100401" required="true" displayOrder="0">
			<rule min="20011001" max="21001231" step="1" validateDate="true" />
		</RateKey>
		<RateKey name="g1" label="年金支払期間" type="combo" required="true"
			displayOrder="14" selectedIndex="1">
			<items>
				<item label="0" value="0" />
				<item label="5" value="5" />
				<item label="10" value="10" />
				<item label="15" value="15" />
			</items>
			<rule min="0" max="15" step="5" />
		</RateKey>
		<RateKey name="g2" label="年金支払保証期間" type="combo" required="true"
			displayOrder="15" selectedIndex="1">
			<items>
				<item label="0" value="0" />
				<item label="5" value="5" />
				<item label="10" value="10" />
				<item label="15" value="15" />
			</items>
			<rule min="0" max="15" step="5" />
		</RateKey>
		<RateKey name="insuranceCode" label="保険種類" type="combo"
			required="true" displayOrder="1" selectedIndex="0">
			<items>
				<item label="931" value="931" />
				<item label="932" value="932" />
				<item label="933" value="933" />
				<item label="934" value="934" />
			</items>
			<rule min="931" max="934" step="1" />
		</RateKey>
		<RateKey name="annuityType" label="年金の種類" type="radio"
			required="true" selectedIndex="0" displayOrder="2">
			<items>
				<item label="確定" value="50" />
				<item label="終身" value="51" />
			</items>
			<rule min="50" max="51" step="1" />
		</RateKey>

		<RateKey name="kisoritsu" label="計算基礎" type="combo"
			displayOrder="1" selectedIndex="0" required="true">
			<items>
				<item label="P" value="0" />
				<item label="V" value="1" />
				<item label="H" value="2" />
			</items>
			<rule min="0" max="2" step="1" />
		</RateKey>

		<RateKey name="z" label="チルメル" type="text" displayOrder="32"
			initValue="0" required="true">
			<rule min="0" max="110" step="1" />
		</RateKey>
		<RateKey name="responsibilityDate" label="責任開始日" type="text"
			initValue="20100401" required="true" displayOrder="70">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>
	</RateKeys>
</RateKey-definition>

=== dtune/feeling/settings/rateKey/extend.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
  	<!-- レートキーの制御関係 -->
  	<Constraints>
  		<Constraint keys="n,m" condition="(m&lt;99&amp;&amp;n>=m}||(m==99)"
  		 desc="保険期間は払込期間より大きいで入力ください。"/>
  	</Constraints>
  	  	
  	<!-- レートキーのUI属性 -->
    <RateKeys>
        <RateKey name="L" label="貸付金" type="text"
         required="true" initValue="0" displayOrder="97">
          <rule min="0" max="999999999" step="1"/>
        </RateKey>
        <RateKey name="SurrenderFeeS" label="解約返戻金" type="text"
         required="true" initValue="1000000" displayOrder="96">
          <rule min="0" max="999999999" step="1"/>
        </RateKey>
        <RateKey name="extendPremium" label="死亡保険金額" type="text"
         initValue="1000000" required="true" displayOrder="31">
        	<rule max="999999999" min="0" step="1"/>
        </RateKey>
    </RateKeys>
</RateKey-definition>

=== dtune/feeling/settings/rateKey/204.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
	<!-- レートキーの制御関係 -->
	<Constraints>
		<Constraint keys="n,m" condition="(m&lt;99&amp;&amp;n>=m)||(m==99)"
			desc="保険期間は払込期間より大きいで入力ください。" />
		<Constraint keys="kaisu,m"
			condition="(kaisu==1&amp;&amp;m==0)||(kaisu&gt;1&amp;&amp;m&gt;0)"
			desc="一時払いの場合、払込期間は0となければならない;分割払の場合、払込期間は0以上で入力ください。" />
	</Constraints>

	<!-- レートキーのUI属性 -->
	<RateKeys>
		<RateKey name="n" label="保険期間" type="text" required="true"
			initValue="34" displayOrder="2">
			<rule min="0" max="99" step="1" />
		</RateKey>
		<RateKey name="m" label="払込期間" type="text" required="true"
			initValue="15" displayOrder="3">
			<rule min="0" max="99" step="1" />
		</RateKey>
		<RateKey name="sex" label="性別" type="radio" required="true"
			displayOrder="3" selectedIndex="0">
			<items>
				<item label="男性" value="0" />
				<item label="女性" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="x" label="被年令" type="text" required="true"
			initValue="16" displayOrder="4">
			<rule min="0" max="99" step="1" />
		</RateKey>
		<RateKey name="contractorType" label="被保険者型" type="combo"
			selectedIndex="1" required="true" displayOrder="4">
			<items>
				<item label="-" value="0" />
				<item label="本人型" value="1" />
				<item label="本配型" value="2" />
				<item label="本配子型" value="3" />
				<item label="本子型" value="4" />
			</items>
			<rule min="1" max="4" step="1" />
		</RateKey>
		<RateKey name="kaisu" label="払込回数" type="combo" required="true"
			displayOrder="7" selectedIndex="1">
			<items>
				<item label="一時払" value="1" />
				<item label="年払" value="2" />
				<item label="半年払" value="3" />
				<item label="月払" value="4" />
			</items>
			<rule min="1" max="5" step="1" />
		</RateKey>
		<RateKey name="state" label="契約状態" type="combo" required="true"
			displayOrder="8" selectedIndex="1">
			<items>
				<item label="-" value="0" />
				<item label="保険料払込期間中" value="1" />
				<item label="保険料払込期間終了後" value="2" />
				<item label="払込免除" value="6" />
			</items>
			<rule min="0" max="6" step="1" />
		</RateKey>
		<RateKey name="keiro" label="払込経路" type="combo" required="true"
			displayOrder="9" selectedIndex="2">
			<items>
				<item label="-" value="0" />
				<item label="普通" value="1" />
				<item label="口座振替" value="2" />
				<item label="団体保険料A" value="3" />
				<item label="団体保険料B" value="4" />
				<item label="集団扱" value="5" />
			</items>
			<rule min="1" max="5" step="1" />
		</RateKey>
		<RateKey name="sptate" label="S/P建" type="radio" required="true"
			displayOrder="10" selectedIndex="0">
			<items>
				<item label="S建" value="0" />
				<item label="P建" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="t" label="経過年" type="text" required="true"
			displayOrder="10">
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="f" label="経過月" type="text" required="true"
			displayOrder="11">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="t1" label="払込年" type="text" required="true"
			displayOrder="12">
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="f1" label="払込月" type="text" required="true"
			displayOrder="13">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="SA" label="基本S" type="text" required="true"
			displayOrder="14" initValue="10000">
			<rule min="0" max="999999999" step="1" />
		</RateKey>

		<RateKey name="i" label="支払限度" type="combo" required="true"
			displayOrder="29" selectedIndex="1">
			<items>
				<item label="-" value="0" />
				<item label="120" value="120" />
				<item label="360" value="360" />
				<item label="730" value="730" />
			</items>
			<rule min="120" max="730" step="10" />
		</RateKey>
		<RateKey name="contractDate" label="契約日" type="text"
			initValue="20100401" required="true" displayOrder="0">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>

		<RateKey name="kisoritsu" label="計算基礎" type="combo"
			displayOrder="1" selectedIndex="0" required="true">
			<items>
				<item label="P" value="0" />
				<item label="V" value="1" />
				<item label="H" value="2" />
			</items>
			<rule min="0" max="2" step="1" />
		</RateKey>

		<RateKey name="z" label="チルメル期間" type="text" displayOrder="32"
			initValue="0" required="true">
			<rule min="0" max="110" step="1" />
		</RateKey>

		<RateKey name="PremiumAbolishSign" label="保険料不可分の撤廃の対象" type="radio"
			displayOrder="90">
			<items>
				<item label="いいえ" value="0" />
				<item label="はい" value="1" />
			</items>
		</RateKey>

	</RateKeys>
</RateKey-definition>

=== dtune/feeling/settings/rateKey/331.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
	<!-- レートキーの制御関係 -->
	<Constraints>
		<Constraint keys="n,m" condition="(m&lt;99&amp;&amp;n>=m)||(m==99)"
			desc="保険期間は払込期間より大きいで入力ください。" />
	</Constraints>
	<!-- レートキーのUI属性 -->
	<RateKeys>
		<RateKey name="m" label="払込期間" type="text" required="true"
			initValue="3" displayOrder="2">
		</RateKey>
		<RateKey name="x" label="被年令" type="text" required="true"
			initValue="15" displayOrder="4">
			<rule min="0" max="110" step="1" />
		</RateKey>
		<RateKey name="sex" label="性別" type="radio" required="true"
			displayOrder="3" selectedIndex="0">
			<items>
				<item label="男性" value="0" />
				<item label="女性" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="SA" label="基本S" type="text" required="true"
			displayOrder="14" initValue="10000">
			<rule min="0" max="999999999" step="1" />
		</RateKey>
		<RateKey name="kaisu" label="払込回数" type="combo" required="true"
			displayOrder="7" selectedIndex="2">
			<items>
				<item label="一時払" value="1" />
				<item label="年払" value="2" />
				<item label="半年払" value="3" />
				<item label="月払" value="4" />
			</items>
			<rule min="1" max="4" step="1" />
		</RateKey>
		<RateKey name="keiro" label="払込経路" type="combo" required="true"
			displayOrder="9" selectedIndex="0">
			<items>
				<item label="-" value="0" />
				<item label="普通" value="1" />
				<item label="口座振替" value="2" />
				<item label="団体保険料A" value="3" />
				<item label="団体保険料B" value="4" />
				<item label="集団扱" value="5" />
			</items>
		</RateKey>
		<RateKey name="t" label="経過年" type="text" required="true"
			displayOrder="10">
		</RateKey>
		<RateKey name="f" label="経過月" type="text" required="true"
			displayOrder="11">
		</RateKey>
		<RateKey name="tEX" label="延長期間(整数年部分)" type="text" required="true"
			displayOrder="20">
		</RateKey>
		<RateKey name="fEX" label="延長期間(端月数部分)" type="text" required="true"
			displayOrder="21">
		</RateKey>
		<RateKey name="t1" label="払込年" type="text" required="true"
			displayOrder="12">
			<rule min="0" max="90" step="1" />
		</RateKey>
		<RateKey name="f1" label="払込月" type="text" required="true"
			displayOrder="13">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="state" label="契約状態" type="combo" required="true"
			displayOrder="8" selectedIndex="1">
			<items>
				<item label="-" value="0" />
				<item label="保険料払込期間中" value="1" />
				<item label="保険料払込期間終了後" value="2" />
				<item label="払込免除" value="6" />
			</items>
			<rule min="0" max="7" step="1" />
		</RateKey>
		<RateKey name="payStatus" label="払込状態" type="combo" required="true"
			displayOrder="11" selectedIndex="0">
			<items>
				<item label="払込中" value="1" />
				<item label="払込済" value="2" />
			</items>
		</RateKey>
		<RateKey name="sptate" label="S/P建" type="radio" required="true"
			displayOrder="10" selectedIndex="0">
			<items>
				<item label="S建" value="0" />
				<item label="P建" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="contractDate" label="契約日" type="text"
			initValue="20100401" required="true" displayOrder="0">
			<rule min="20000101" max="21001231" step="1" validateDate="true" />
		</RateKey>

		<RateKey name="kisoritsu" label="計算基礎" type="combo"
			displayOrder="1" selectedIndex="0" required="true">
			<items>
				<item label="P" value="0" />
				<item label="V" value="1" />
				<item label="H" value="2" />
			</items>
			<rule min="0" max="2" step="1" />
		</RateKey>

		<RateKey name="z" label="チルメル期間" type="text" displayOrder="32"
			initValue="0" required="true">
			<rule min="0" max="110" step="1" />
		</RateKey>

		<RateKey name="PremiumAbolishSign" label="保険料不可分の撤廃の対象" type="radio"
			displayOrder="90">
			<items>
				<item label="いいえ" value="0" />
				<item label="はい" value="1" />
			</items>
		</RateKey>

	</RateKeys>
</RateKey-definition>

=== dtune/feeling/settings/rateKey/304.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RateKey-definition SYSTEM "RateKey-definition.dtd">
<RateKey-definition>
	<!-- レートキーの制御関係 -->
	<Constraints>
		<Constraint keys="n,m" condition="(m&lt;99&amp;&amp;n>=m)||(m==99)"
			desc="保険期間は払込期間より大きいで入力ください。" />
		<Constraint keys="kaisu,m"
			condition="(kaisu==1&amp;&amp;m==0)||(kaisu&gt;1&amp;&amp;m&gt;0)"
			desc="一時払いの場合、払込期間は0となければならない;分割払の場合、払込期間は0以上で入力ください。" />
		<Constraint keys="l,t,n,state" desc="繰り下げ期間中の場合、繰り下げ期間は経過年月-保険期間となります。"
			condition="if(state==5&amp;&amp;l-t+n&lt;=0){0}else{1}" />
	</Constraints>

	<!-- レートキーのUI属性 -->
	<RateKeys>
		<RateKey name="dividend" label="配当" type="radio" required="false"
			displayOrder="1" selectedIndex="0">
			<items>
				<item label="無" value="0" />
				<item label="有" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="n" label="保険期間" type="text" required="true"
			initValue="34" displayOrder="2">
			<rule min="0" max="99" step="1" />
		</RateKey>
		<RateKey name="m" label="払込期間" type="text" required="true"
			initValue="15" displayOrder="3">
			<rule min="0" max="99" step="1" />
		</RateKey>
		<RateKey name="sex" label="性別" type="radio" required="true"
			displayOrder="3" selectedIndex="0">
			<items>
				<item label="男性" value="0" />
				<item label="女性" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="x" label="被年令" type="text" required="true"
			initValue="16" displayOrder="4">
			<rule min="0" max="75" step="1" />
		</RateKey>
		<RateKey name="kaisu" label="払込回数" type="combo" required="true"
			displayOrder="7" selectedIndex="1">
			<items>
				<item label="一時払" value="1" />
				<item label="年払" value="2" />
				<item label="半年払" value="3" />
				<item label="月払" value="4" />
			</items>
			<rule min="1" max="5" step="1" />
		</RateKey>
		<RateKey name="partOnetime" label="一部一時払" type="radio"
			required="true" displayOrder="6" selectedIndex="0">
			<items>
				<item label="なし" value="0" />
				<item label="あり" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="state" label="契約状態" type="combo" required="true"
			displayOrder="8" selectedIndex="2">
			<items>
				<item label="-" value="0" />
				<item label="保険料払込期間中" value="1" />
				<item label="保険料払込期間終了後" value="2" />
				<item label="払込免除" value="6" />
			</items>
			<rule min="0" max="6" step="1" />
		</RateKey>
		<RateKey name="keiro" label="払込経路" type="combo" required="true"
			displayOrder="9" selectedIndex="2">
			<items>
				<item label="-" value="0" />
				<item label="普通" value="1" />
				<item label="口座振替" value="2" />
				<item label="団体保険料A" value="3" />
				<item label="団体保険料B" value="4" />
				<item label="集団扱" value="5" />
			</items>
			<rule min="1" max="5" step="1" />
		</RateKey>
		<RateKey name="sptate" label="S/P建" type="radio" required="true"
			displayOrder="10" selectedIndex="0">
			<items>
				<item label="S建" value="0" />
				<item label="P建" value="1" />
			</items>
			<rule min="0" max="1" step="1" />
		</RateKey>
		<RateKey name="t" label="経過年" type="text" required="true"
			displayOrder="10">
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="f" label="経過月" type="text" required="true"
			displayOrder="11">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="t1" label="払込年" type="text" required="true"
			displayOrder="12">
			<rule min="0" max="111" step="1" />
		</RateKey>
		<RateKey name="f1" label="払込月" type="text" required="true"
			displayOrder="13">
			<rule min="0" max="12" step="1" />
		</RateKey>
		<RateKey name="SA" label="保険料・保険金" type="text" required="true"
			displayOrder="14" initValue="10000">
			<rule min="0" max="999999999" step="1" />
		</RateKey>
		<RateKey name="finalPercent" label="最終保険金額割合" type="combo"
			required="true" displayOrder="26" selectedIndex="0">
			<items>
				<item label="２０％型" value="0" />
				<item label="４０％型" value="1" />
				<item label="６０％型" value="2" />
			</items>
			<rule min="0" max="2" step="1" />
		</RateKey>
		<RateKey name="contractDate" label="契約日" type="text"
			initValue="20100401" required="true" displayOrder="0">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>

		<RateKey name="kisoritsu" label="計算基礎" type="combo"
			displayOrder="1" selectedIndex="0" required="true">
			<items>
				<item label="P" value="0" />
				<item label="V" value="1" />
				<item label="H" value="2" />
			</items>
			<rule min="0" max="2" step="1" />
		</RateKey>

		<RateKey name="z" label="チルメル期間" type="text" displayOrder="32"
			initValue="0" required="true">
			<rule min="0" max="110" step="1" />
		</RateKey>

		<RateKey name="PremiumAbolishSign" label="保険料不可分の撤廃の対象" type="radio"
			displayOrder="90">
			<items>
				<item label="いいえ" value="0" />
				<item label="はい" value="1" />
			</items>
		</RateKey>

		<RateKey name="responsibilityDate" label="責任開始日" type="text"
			initValue="20100401" required="true" displayOrder="70">
			<rule min="19960930" max="21001231" step="1" validateDate="true" />
		</RateKey>
	</RateKeys>
</RateKey-definition>
