=== dtune/feeling/settings/formula/insurance/Formula-definition.dtd
<!ELEMENT BizExpenses ( formula+ ) >
<!ATTLIST BizExpenses desc CDATA #REQUIRED >

<!ELEMENT Common ( formula+ ) >
<!ATTLIST Common desc CDATA #REQUIRED >

<!ELEMENT Formula-definition ( BizExpenses, Common, Premium, ReserveFund, SurrenderFee ) >
<!ELEMENT common-formula ( Common ) >
<!ELEMENT Benefit-formula ( Common ) >
<!ELEMENT LifePension-formula ( Common ) >

<!ELEMENT Premium ( formula+ ) >
<!ATTLIST Premium desc CDATA #REQUIRED >

<!ELEMENT ReserveFund ( formula+ ) >
<!ATTLIST ReserveFund desc CDATA #REQUIRED >

<!ELEMENT SurrenderFee ( formula+ ) >
<!ATTLIST SurrenderFee desc CDATA #REQUIRED >

<!ELEMENT formula ( #PCDATA | formula )* >
<!ATTLIST formula accessable ( true | false ) #IMPLIED >
<!ATTLIST formula mate ( true | false ) #IMPLIED >
<!ATTLIST formula cacheable ( true | false ) #IMPLIED >
<!ATTLIST formula disaster ( true | false ) #IMPLIED >
<!ATTLIST formula desc CDATA #IMPLIED >
<!ATTLIST formula name CDATA #REQUIRED >
<!ATTLIST formula fundCode CDATA #IMPLIED >
<!ATTLIST formula pvh CDATA #IMPLIED >
<!ATTLIST formula limitedAge CDATA #IMPLIED >
<!ATTLIST formula limitedSex ( male | female ) #IMPLIED >
<!ATTLIST formula paras CDATA #IMPLIED >
<!ATTLIST formula value NMTOKEN #IMPLIED >
<!ATTLIST formula fraction CDATA #IMPLIED >
<!ATTLIST formula xtime ( 0 | 1 | 4 ) #IMPLIED >

=== dtune/feeling/settings/formula/insurance/307.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<BizExpenses desc="事業費率の設定">
		<formula name="alphaL" fraction="8" desc="生存α">
			0.017*sum(1,n){I(index)}
		</formula>
		<formula name="alphaD" desc="死亡α">
			roundDown(0.006*min{roundDown(n/10,2),1},8)
		</formula>
		<formula name="deltaL" desc="生存δ">
			if(kaisu==1){0}else{roundDown(0.02*min{roundDown(max{m,10}/20,2),1},8)}
		</formula>
		<formula name="deltaD" fraction="3" desc="死亡δ">
			if(kaisu==1){
				max{0.04-0.01/5*max{x+n-55,0},0}
			}else{
				max{0.06-0.01/5*max{x+n-55,0},0}
			}
		</formula>

		<formula name="gammaL" fraction="8" desc="生存γ">
			0.001*sum(1,n){index*I(index)}/n
		</formula>
		<formula name="gammaD" desc="死亡γ">
			if(gen==1){0.00115}else{0.00105}
		</formula>
		<formula name="gamma1L" fraction="8" desc="生存γ'">
			0.001*sum(1,n){index*I(index)}/n
		</formula>
		<formula name="gamma1D" value="0.001" desc="死亡γ'"/>
		<formula name="beta" value="0.03" desc="集金費β"/>
		<formula name="zeta" desc="集金費ζ">
			if(gen==1){0.04}
			elseIf(gen==2){0.03}
			else{0.025}
		</formula>
		<formula name="epsilon" desc="免費用ε">
			if(m&lt;=5){0.0005}
			elseIf(m&gt;5 &amp;&amp; m&lt;=10){0.0010}
			else{0.0020}
		</formula>
		<formula name="I" paras="j" desc="生存給付金割合">
			if(j==n){
				if(n%3==0){
					0.2
				}else{0}
			}elseIf(j&gt;0 &amp;&amp; j&lt;n &amp;&amp; j%3==0){0.1}
			else{0}
		</formula>
		<formula name="d" desc="高額割引率">
			if(xtime&gt;0){
				0
			}else{
				if(gen==1){
					if(SA&lt;25000000){
						0
					}else{
						0.00001
					}
				}elseIf(gen==2){
					if(SA&lt;15000000){
						0
					}elseIf(SA&gt;=15000000 &amp;&amp; SA&lt;25000000){
						0.000005
					}elseIf(SA&gt;=25000000 &amp;&amp; SA&lt;45000000){
						0.000015
					}else{
						0.00003
					}
				}elseIf(gen==3){
					if(SA&lt;20000000){
						0
					}elseIf(SA&gt;=20000000 &amp;&amp; SA&lt;50000000){
						0.00002
					}else{
						0.00004
					}
				}else{
					0
				}
			}
		</formula>
	</BizExpenses>

	<Common desc="商品内部の共通公式">
		<!-- 下記の分割払いの係数定義は商品に問わずため、外部の共通commonフォルダに移す -->
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="6" desc="払込方法別Prate">
			<!-- 基準Prateと高額割引dより、払込方法別Prateを求める -->
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){0}
				elseIf(kaisu==2){12*d}
				elseIf(kaisu==3){6*d}
				else{d}
			</formula>
			stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d)
		</formula>
		
		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
				<!-- 普通の場合 -->
				if(kaisu==1){
					round(1/SBasePrate,4)
				}else{
					round(1/SBasePrate,2)
				}
		</formula>
	</Common>
	
	<Premium desc="保険料">
		<!-- 基準Prate STR -->
		<formula name="stdPrate" pvh="P" accessable="false" desc="基準保険料レート">
			<!-- 当該商品には分割払いしかない -->
			if(kaisu==1){singlePrate}else{MultiPrate}
			<!-- 一時払 STR -->
			<formula name="singlePrate" fraction="5" desc="一時払Pレート">
				sum(1,n){I(index)*A_x_n_l(x,index)}+alphaL+gamma1L*a_x_n(x,n)
				+
				(A_x_n_D(x,n)+alphaD+gamma1D*a_x_n(x,n))/(1-deltaD)
			</formula>
			<!-- 一時払 END -->
			<!-- 分割払 STR -->
			<formula name="MultiPrate" fraction="6" desc="分割払Pレート">
				PL+PD
				<formula name="PL" accessable="false" desc="基準Pレート生存部分">
					<!-- (sum(1,n){I(index)*A_x_n_l(x,index)}+alphaL+gammaL*a_k_x_n(12,x,m)+gamma1L*f_a_n(m,n))
					/
					(12*(1-beta-zeta-deltaL-epsilon)*a_k_x_n(12,x,m)) -->
					<!-- 現行SYSTEMの算式 -->
					(sum(1,n){I(index)*A_x_n_l(x,index)}+alphaL+gammaL*a_k_x_n(12,x,m)+gamma1L*f_a_x_n(m,x,n))
					/
					(12*(1-beta-zeta-deltaL-epsilon)*a_k_x_n(12,x,m))
				</formula>
				<formula name="PD" accessable="false" desc="基準Pレート死亡部分">
					<!-- (A_x_n_D(x,n)+alphaD+gammaD*a_k_x_n(12,x,m)+gamma1D*f_a_n(m,n))
					/ 
					(12*(1-beta-zeta-deltaD-epsilon)*a_k_x_n(12,x,m)) -->
					<!-- 現行SYSTEMの算式 -->
					(A_x_n_D(x,n)+alphaD+gammaD*a_k_x_n(12,x,m)+gamma1D*f_a_x_n(m,x,n))
					/ 
					(12*(1-beta-zeta-deltaD-epsilon)*a_k_x_n(12,x,m))
				</formula>
			</formula>
			<!-- 分割払 END -->
		</formula>
		<!-- 基準Prate END -->

		<formula name="PrateByYear" pvh="P" fraction="6" desc="年払Prate">
			stdPrate*PayFactor(2,gen,1)-12*d
		</formula>

		<formula name="Prate" pvh="P" accessable="true" desc="１．保険料レート">
			PrateByPaymode(stdPrate,d)
		</formula>

		<formula name="Premium" pvh="P" fundCode="307" accessable="true" desc="２．保険料・保険金">
			<!-- 高額割引がゼロ 100円の位を切り上げ-->
			if(sptate==0){
				roundDown(SA*Prate,0)
			}else{
				roundUp(
						roundDown(
							SA*S2P(Prate)
							,0)/1000
					,0)*1000
			}
		</formula>
	</Premium>

	<ReserveFund desc="責任準備金">
		<!-- 年金支払開始前 -->
		<!-- 保険年度末保険料積立金rate STR -->
		<formula name="MultiV" paras="t,z" desc="保険料払込期間中/保険料払込免除契約のVTレート">
			 max{
			 	A_xt_nt_D(x,t,n)+sum(t,n){I(index)*A_xt_nt_l(x,index,t)}+(gamma1L+gamma1D)*a_x_n(x+t,n-t)
			 		-
			 	(A_x_n_D(x,n)+sum(1,n){I(index)*A_x_n_l(x,index)}+(gamma1L+gamma1D)*a_x_n(x,n))/a_x_n(x,m)*a_x_n(x+t,m-t)
			 		-
			 	if(z==0){0}else{alphaZ/a_x_n(x,z)*a_x_n(x+t,z-t)}
			 ,0}
			 <formula name="alphaZ">
			 	0.017*sum(1,n){I(index)}+0.008*min(n/10,1)
			 </formula>
		</formula>
		
		<formula name="SingleV" paras="t" fraction="4" desc="保険料払込期間終了後/一時払のVTレート">		
			A_xt_nt_D(x,t,n)+sum(t,n){I(index)*A_xt_nt_l(x,index,t)}+(gamma1L+gamma1D)*a_x_n(x+t,n-t)			
		</formula>
		
		<formula name="subVrate1" paras="t,z">
			A_xt_nt_D(x,t,n)+sum(t,n){I(index)*A_xt_nt_l(x,index,t)}+(gamma1L+gamma1D)*a_x_n(x+t,n-t)
				-
			(PrateByYear+gamma1L+gamma1D)*a_x_n(x+t,m-t)
				-
			if(z==0){0}else{(0.017*sum(1,n){I(index)}+0.008*min{n/10,1})/a_x_n(x,z)*a_x_n(x+t,z-t)}
		</formula>
		
		<formula name="subVrate2" paras="t" fraction="6">
			(A_x_n_D(x,n)+sum(1,n){I(index)*A_x_n_l(x,index)}+(gamma1L+gamma1D)*f_a_x_n(m,x,n))/a_x_n(x,m)
		</formula>
		
		<formula name="Vrate_accu" paras="t,z" desc="保険年度末rate">
			if(state==1||state==6){
				<!-- 保険料払込期間中/保険料払込免除契約 -->
				MultiV(t,z)
			}elseIf(state==2||kaisu==1){
				<!-- 保険料払込期間終了後/一時払 -->
				SingleV(t)
			}else{0}
		</formula>
		<formula name="Vrate" fraction="4" pvh="H" accessable="true" desc="１．保険年度末Vレート">
			Vrate_accu(t,0)
		</formula>
		<!-- 保険年度末保険料積立金rate END -->

		<!-- 契約者用Vrate STR -->
		<formula name="ContractorYearV" pvh="P" paras="t,z" fraction="4" desc="保険年度末VTレート">
			Vrate_accu(t,z)
		</formula>
		<formula name="ContractorVrate" fraction="4" pvh="P" accessable="true" desc="３．契約者用Vレート">
			if(state==1||state==6){
			<!-- 保険料払込期間中/保険料払込免除契約 -->
				set{t1_bak=t1}
				set{t1=if(t1==t+1&amp;&amp;f1==0){t1-1}else{t1}}
				set{f1=if(t1==t1_bak-1){12}else{f1}}
				max((1-f_12(f1))*(ContractorYearV(t1,z)-I(t1))+f_12(f1)*ContractorYearV(t1+1,z),0)
			}elseIf(state==2||kaisu==1){
			<!-- 保険料払込期間終了後/一時払 -->
				max((1-f_12(f))*(ContractorYearV(t,z)-I(t))+f_12(f)*ContractorYearV(t+1,z),0)
			}else{0}
		</formula>
		<!-- 契約者用Vrate END -->
		
		<formula name="BizYearV" paras="t,z" accessable="false" desc="事業末Vレート">
			if(state==1){
				<!-- 保険料払込期間中 -->
				if(subVrate2(t)&lt;=PrateByYear){
					MultiV(t,z)
				}else{
					max{subVrate1(t,z),0}
				}
			}elseIf(state==2||kaisu==1||state==6){
				<!-- 保険料払込期間終了後/一時払/保険料払込免除契約 -->
				SingleV(t)
			}else{0}
		</formula>
		
		<formula name="calBizYearV" fraction="4" desc="事業末用Vレート">
			BizYearV(t,z)
		</formula>
		
	</ReserveFund>

	<SurrenderFee desc="解約返戻金">
		<formula name="sigma" paras="t">
			if(min{m,10}&gt;=t){
				(0.013*sum(1,n){I(index)}+0.006*min{n/10,1})*(min{m,10}-t)/min{m,10}
			}else{
				0
			}
		</formula>

		<!-- Wrate STR -->
		<formula name="tWrate" pvh="P" paras="t">
			if(state==1||state==6){
				<!-- 保険料払込期間中/保険料払込免除契約 -->
				round(max{ContractorYearV(t1,0)-I(t1)-sigma(t1),0},4)
			}elseIf(state==2||kaisu==1){
				<!-- 保険料払込期間終了後/一時払 -->
				max{round(ContractorYearV(t,0)-I(t),4),0}
			}else{0}
		</formula>
		<formula name="tWrate1" pvh="P" paras="t">
			if(state==1||state==6){
				<!-- 保険料払込期間中/保険料払込免除契約 -->
				round(max{ContractorYearV(t1+1,0)-sigma(t1+1),0},4)
			}elseIf(state==2||kaisu==1){
				<!-- 保険料払込期間終了後/一時払 -->
				max{ContractorYearV(t+1,0),0}
			}else{0}
		</formula>
		<!-- Wrate END -->

		<!-- 解約返戻金rate STR -->
		<formula name="Wrate" fraction="4" pvh="P" accessable="true" desc="１．解約返戻金Wレート">
			<formula name="Wrate_Overbar1">
				set{z=min{m,5}}
				v^ve
					*
				round((1-f_12(f1))*min{tWrate(t1),max(round(MultiV_W(t1,z)-I(t1),4),0)}+f_12(f1)*min{tWrate1(t1),MultiV_W(t1+1,z)},4)
				<formula name="MultiV_W" paras="t,z" pvh="V" fraction="4" desc="保険料払込期間中/保険料払込免除契約のVTレート">
					 MultiV(t,z)
				</formula>
			</formula>
			if(state==1||state==6){
				<!-- 保険料払込期間中/保険料払込免除契約 -->
				set{t1_bak=t1}
				set{t1=if(t1==t+1&amp;&amp;f1==0){t1-1}else{t1}}
				set{f1=if(t1==t1_bak-1){12}else{f1}}
				max(Wrate_Overbar1,0)
			}elseIf(state==2||kaisu==1){
				<!-- 保険料払込期間終了後/一時払 -->
				(1-f_12(f))*tWrate(t)+f_12(f)*tWrate1(t)
			}else{0}
		</formula>
		<!-- 解約返戻金rate END -->
	</SurrenderFee>

</Formula-definition>

=== dtune/feeling/settings/formula/special/235.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="special_b_Prate_self" xtime="4" desc="4倍体本人部分疾病合計(Pレート)">
			if(kaisu==1){
				Honnin_b_Yj(n1,m1)
			}else{
				Honnin_b_Bk(n1,m1)
			}
		</formula>
		<formula name="normal_b_Prate_self" xtime="1" desc="1倍体本人部分疾病合計(Pレート)">
			if(kaisu==1){
				Honnin_b_Yj(n1,m1)
			}else{
				Honnin_b_Bk(n1,m1)
			}
		</formula>
		<formula name="normal_z_Prate_self" xtime="1" desc="1倍体本人災害部分合計(Pレート)">
			if(kaisu==1){
				Honnin_z_Yj(n1,m1)
			}else{
				Honnin_z_Bk(n1,m1)
			}
		</formula>
		<formula name="normalPrate" desc="1倍体基準Prate">
			normal_b_Prate_self + normal_z_Prate_self	
		</formula>
		<formula name="specialPrate" desc="4倍体基準Prate">
			special_b_Prate_self + normal_z_Prate_self	
		</formula>
		<formula name="Special_stdPrate" desc="特別条件付基準Prate" fraction="3">
			if(kaisu==1){
				(specialLambda-1)*(specialPrate-normalPrate)/(specialLambda1-1)
			}else{
				(specialLambda-1)*(specialPrate-normalPrate)/(specialLambda1-1)
			}
		</formula>
		<formula name="Special_Prate" pvh="P" desc="特別条件付Prate">
			PrateByPaymode(Special_stdPrate,0)
		</formula>
		<formula name="Special_Premium" pvh="P" accessable="true" desc="特別条件付保険料/保険金額">
			<!--Ｓ建てとして計算する -->
			roundDown(SA*max(PrateByPaymode(Special_stdPrate,0),0),0)
		</formula>
	</Premium>

	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
		<formula name="x4ContractorVrate" xtime="4" desc="4倍体契約者用レート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			ContractorVrate
		</formula>
		
		<formula name="x1ContractorVrate" xtime="1" desc="1倍体契約者用レート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			ContractorVrate
		</formula>
		<formula name="Special_ContractorVrate" pvh="P" accessable="true" fraction="2" paras="t" desc="特体契約者レート">
			(specialLambda-1)*(x4ContractorVrate-x1ContractorVrate)/(specialLambda1-1)
		</formula>
		<formula name="Special_Valuation" accessable="true" fraction="0" pvh="P" desc="特体契約者実額">
			max(SA*Special_ContractorVrate,0)
		</formula>
		<formula name="x4BizYear" xtime="4" fraction="2" accessable="false" desc="4倍体事業年度末用Vレート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			BizYearV(t)
		</formula>
		<formula name="x1BizYear" xtime="1" fraction="2" accessable="false" desc="1倍体事業年度末用Vレート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			BizYearV(t)
		</formula>
		<formula name="Special_BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="2" accessable="true" desc="特体事業年度末レート">
			(specialLambda-1)*(x4BizYear-x1BizYear)/(specialLambda1-1)
		</formula>
		<formula name="Special_BizYearValuation" fraction="0" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="特体業年度末実額">
			SA*Special_BizYearVate
		</formula>		
	</ReserveFund>
</Formula-definition>

=== dtune/feeling/settings/formula/insurance/931.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
     <BizExpenses desc="事業費率の設定">
           <formula name="alphaE">
             if(insuranceCode==931||insuranceCode==933){0}else{0.017}
           </formula>
           <formula name="gamma2" value="0.01"/>
     </BizExpenses>
     
     <Common desc="商品内部の共通公式">
     	<formula name="xx">
     		x+n
     	</formula>
     	<formula name="tt">
        	t-n
        </formula>
        <formula name="g">
        	if(insuranceCode==931||insuranceCode==932){g1}
        	else{g2}
        </formula>
        <formula name="theta">
        	if(annuityType==50){0}else{5}
        </formula>
     	<formula name="a_g" paras="x" fraction="5">
			(1-v^x)/(1-v)
		</formula>
        <formula name="Iag" fraction="5">
            sum(0,g-1){v^index*(1+theta/100*index)}
        </formula>
        <formula name="Iay" paras="x" fraction="5">
            (1/D[x])*sum(g,omega-x){D[x+index]*(1+theta/100*index)}
        </formula>
        <formula name="sum_Ia" paras="t" fraction="5">
            if(t&gt;=g){0}
            else{
               sum(t,g-1){v^(index-t)*(1+theta/100*index)}
            }
        </formula>
        <formula name="sum_yt" paras="x,t" fraction="5">
            (1/D[x+t])*sum(max(t,g),omega-x){D[x+index]*(1+theta/100*index)}
        </formula>         	 
     </Common>
     
     <Premium desc="保険料">
        <formula name="sPrate" fraction="5" pvh="P" accessable="true" desc="１.保険料レート">
            (1+alphaE)*Fy
            <formula name="Fy" fraction="3">
                if(insuranceCode==934||insuranceCode==933){(1+gamma2)*(Iag+Iay(xx))}
                else{(1+gamma2)*a_g(g)}
            </formula>
        </formula>        
        <formula name="Premium" pvh="P" accessable="true" desc="２．保険料/保険金額">
			if(sptate==1){
				roundUp(roundDown(SA/sPrate,0)/1000,0)*1000
			}else{
				round(SA*sPrate,0)
			}
		</formula> 
    </Premium>
    
    <ReserveFund desc="保険積立金">
        <formula name="lifePension" paras="x,t" desc="終身年金">
			<!--if(t&lt;g||benefitRequest==50){(1+gamma2)*sum_yt(x,t)}-->
			(1+gamma2)*(sum_Ia(t)+sum_yt(x,t))
        </formula>
        
        <formula name="certainAnnuity" paras="t" desc="確定年金">
            (1+gamma2)*a_g(max(g-t,0))
        </formula>
        
        <formula name="Vrate_accu" paras="tt" desc="保険年度末rate">
             if(insuranceCode==934||insuranceCode==933){lifePension(xx,tt)}
             else{certainAnnuity(tt)}
        </formula>
        <formula name="Vrate" accessable="true" fraction="3" pvh="H" desc="１.保険年度末Ｖレート">
             if(insuranceCode==934||insuranceCode==933){lifePension(xx,tt)}
             else{certainAnnuity(tt)}
        </formula>

        <formula name="ContractorYearV" paras="x,t" pvh="P" fraction="3" desc="保険年度契約者VTレート">
            if(insuranceCode==934||insuranceCode==933){lifePension(x,t)}else{certainAnnuity(t)}
        </formula>
        
		<formula name="ContractorVrate" pvh="P" fraction="3" accessable="true" desc="３.契約者用Ｖレート">
			if(f==0){
				ContractorYearV(xx,tt)
			}else{
				v^((12-f)/12)*ContractorYearV(xx,tt+1)
			}
		</formula>
		
		<formula name="BizYearV" paras="t" fraction="3" accessable="false" desc="事業末Vレート">
             if(insuranceCode==934||insuranceCode==933){lifePension(xx,tt)}
             else{certainAnnuity(tt)}
        </formula>
        
		<formula name="VrateValuation" pvh="H" fraction="0" accessable="true" desc="４．保険年度末実額">
			SA*Vrate
		</formula>
		<formula name="Valuation" pvh="P" fraction="0" accessable="true" desc="５．契約者責任準備金実額">
			SA*ContractorVrate
		</formula>
		<formula name="BizYearValuation" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="0" accessable="true" desc="６．事業年度末実額">
			SA*BizYearV
		</formula>
		
	</ReserveFund>
    
    <SurrenderFee desc="解約返戻金">
         <formula name="CashValue" pvh="P" fraction="0" accessable="true" desc="解約返戻金実額">
		     <!-- 取扱なし -->
			 0
	     </formula>
    </SurrenderFee>
</Formula-definition>

=== dtune/feeling/settings/formula/special/028.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="x4Prate" xtime="4" desc="4倍体基準Prate">
			stdPrate
		</formula>
		<formula name="x1Prate" xtime="1" desc="1倍体基準Prate">
			stdPrate
		</formula>
		<formula name="Special_stdPrate" fraction="4" desc="特別条件付基準Prate">
			(specialLambda-1)*(x4Prate-x1Prate)/(specialLambda1-1)+0.000000000001
		</formula>
		<formula name="Special_Prate" pvh="P" desc="特別条件付Prate">
			PrateByPaymode(Special_stdPrate,0)
		</formula>
		<formula name="Special_Premium" pvh="P" accessable="true" desc="特別条件付保険料/保険金額">
			<!--Ｓ建てとして計算する -->
			roundDown(SA*max(PrateByPaymode(Special_stdPrate,0),0),0)
		</formula>
		
		<!--統計側依赖「統計側からの対応作業依頼.xls」-->
		<formula name="x4sts_stdPL" xtime="4" desc="統計側特体生存Pレート">
			sts_stdPL
		</formula>
		<formula name="x4sts_stdPD" xtime="4" desc="統計側特体死亡Pレート">
			sts_stdPD
		</formula>
		<formula name="x1sts_stdPL" xtime="1" desc="統計側標体生存Pレート">
			sts_stdPL
		</formula>
		<formula name="x1sts_stdPD" xtime="1" desc="統計側標体死亡Pレート">
			sts_stdPD
		</formula>
		<formula name="sts_stdPLSpecial" fraction="4" desc="統計側生存特体Prate">
			(specialLambda-1)/(specialLambda1-1)*(x4sts_stdPL-x1sts_stdPL)
		</formula>
		<formula name="sts_stdPDSpecial" fraction="4" desc="統計側死亡特体Prate">
			(specialLambda-1)/(specialLambda1-1)*(x4sts_stdPD-x1sts_stdPD)
		</formula>		
		<formula name="stsPLSpecial" pvh="P" desc="統計側生存特別条件付保険料">
			roundDown(SA*PrateByPaymode(sts_stdPLSpecial,0),0)
		</formula>
		<formula name="stsPDSpecial" pvh="P" desc="統計側死亡特別条件付保険料">
			roundDown(SA*PrateByPaymode(sts_stdPDSpecial,0),0)
		</formula>
	</Premium>

	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
		<formula name="normalPrate" pvh="P" xtime="0" fraction="4" desc="標準体Prate">
			PayFactor(2,gen,1)*stdPrate-12*d
		</formula>

		<formula name="x4ContractorVrate" xtime="4" desc="4倍体契約者用レート">
			ContractorVrate
		</formula>
		<formula name="x1ContractorVrate" xtime="1" desc="1倍体契約者用レート">
			ContractorVrate
		</formula>
		<formula name="Special_ContractorVrate" pvh="P" accessable="true" fraction="3" desc="特体契約者レート">
			(specialLambda-1)*(x4ContractorVrate-x1ContractorVrate)/(specialLambda1-1)
		</formula>
		<formula name="Special_Valuation" fraction="0" pvh="P" accessable="true" desc="特体契約者実額">
		 	max(SA*Special_ContractorVrate,0)
		</formula>
		<formula name="x4BizYear" xtime="4" fraction="3" accessable="false" desc="4倍体事業年度末用Vレート">
			<formula name="special_yearPrate" fraction="4" pvh="P" desc="比較用の特体年払Prate">
				round((x4Prate-x1Prate)*PayFactor(2,gen,1),4)+normalPrate
			</formula>
			set{z=0}
			if(state==1){
            <!-- 払込中-->
            	set{e1=((1+gamma2)*A_xt_nt(x,n,0)+I*A_xt_nt_l(x,n,0)+(gammaD_nashu+gammaL_nashu)*f_a_x_n(m,x,n))/a_x_n(x,m)}	
            	if(round(e1,4)&lt;=special_yearPrate){
				max{
					(1+gamma2)*A_xt_nt(x,n,t)+I*A_xt_nt_l(x,n,t)+(gammaD_nashu+gammaL_nashu)*ft_a_xt_n(m,t,x,n)
						-
					((1+gamma2)*A_xt_nt(x,n,0)+I*A_xt_nt_l(x,n,0)+(gammaD_nashu+gammaL_nashu)*f_a_x_n(m,x,n))/a_x_n(x,m)*a_x_n(x+t,m-t)
						-
					if(z==0){0}else{A_Z*a_x_n(x+t,z-t)/a_x_n(x,z)}
				,0}
            	}else{
            		max{
					(1+gamma2)*A_xt_nt(x,n,t)+I*A_xt_nt_l(x,n,t)+(gammaD_nashu+gammaL_nashu)*ft_a_xt_n(m,t,x,n)
						-
					special_yearPrate*a_x_n(x+t,m-t)
						-
					if(z==0){0}else{A_Z*a_x_n(x+t,z-t)/a_x_n(x,z)}
				    ,0}
            	}
			}elseIf(state==2||state==6){
			<!-- 保険料払込期間終了後.払込免除 -->
				(1+gamma2)*A_xt_nt(x,n,t)+I*A_xt_nt_l(x,n,t)+(gammaD_nashu+gammaL_nashu)*a_x_n(x+t,n-t)
			}elseIf(state==3){
			<!-- 年金支払開始以後 -->
				BenifitStartedV
			}elseIf(kaisu==1){
			<!-- 一時払 -->
				(1+gamma2)*A_xt_nt(x,n,t)+I*A_xt_nt_l(x,n,t)+(gamma1L+gamma1D)*a_x_n(x+t,n-t)
			}else{0}
		</formula>
		<formula name="x1BizYear" xtime="1" fraction="3" accessable="false" desc="1倍体事業年度末用Vレート">
			BizYearV(t,0)
		</formula>
		<formula name="Special_BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="3" accessable="true" desc="特体事業年度末レート">
			(specialLambda-1)*(x4BizYear-x1BizYear)/(specialLambda1-1)
		</formula>
		<formula name="Special_BizYearValuation" fraction="0" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="特体業年度末実額">
			SA*Special_BizYearVate
		</formula>
	</ReserveFund>
</Formula-definition>

=== dtune/feeling/settings/formula/common/Benefit.xml
<!DOCTYPE Benefit-formula PUBLIC "Formula" "Formula-definition.dtd">
<!-- 給付現価　共通定義 -->
<Benefit-formula>
	<Common desc="商品内部の共通公式">
		<formula name="R" paras="x,omega">
			sum(0,omega-x-1){M[x+index]}
		</formula>
		<formula name="A_x" paras="x" fraction="6" desc="給付現価（終身）">
			M[x]/D[x]
		</formula>
		<formula name="A_x_n" paras="x,n" fraction="6" desc="給付現価">
			(M[x]-M[x+n]+D[x+n])/D[x]
		</formula>
		<formula name="A_x_n_D" paras="x,n" fraction="6" desc="死亡給付現価">
			(M[x]-M[x+n])/D[x]
		</formula>
		<formula name="A_xt_nt_D" paras="x,t,n" fraction="6" desc="死亡給付現価（経過年あり）">
			(M[x+t]-M[x+n])/D[x+t]
		</formula>
		<formula name="f_A_x_n_D" paras="f,x,n" fraction="6" desc="f年据置死亡給付現価">
			(M[x+f]-M[x+f+n])/D[x]
		</formula>
		<formula name="ft_A_xt_n_D" paras="f,t,x,n" fraction="6" desc="f年据置死亡給付現価（経過年あり）">
			(M[x+f]-M[x+n])/D[x+t]
		</formula>
		<formula name="IA_x_n_D" paras="x,n" fraction="6">
			1/D[x]*(R(x,omega)-R(x+n,omega)-n*M[x+n])
		</formula>
		<formula name="IA_k_x_n_D" paras="k,x,n" fraction="6">
			IA_x_n_D(x,n)-(k-1)/(2*k)*A_x_n_D(x,n)
		</formula>
		<formula name="AT_x" paras="x" fraction="6" desc="解約率込みの給付現価（終身）">
			MD[x]/DT[x]
		</formula>
		<formula name="A_x_n_l" paras="x,n" fraction="6" desc="生存給付現価">
			D[x+n]/D[x]
		</formula>
		<formula name="A_xt_nt_l" paras="x,n,t" fraction="6" desc="生存給付現価（経過年あり）">
			D[x+n]/D[x+t]
		</formula>
		<formula name="f_A_x_n_l" paras="f,x,n" fraction="6" desc="f年据置生存給付現価">
			D[x+n+f]/D[x]
		</formula>
		<formula name="ft_A_xt_n_l" paras="f,t,x,n" fraction="6" desc="f年据置生存給付現価（経過年あり）">
			D[x+n]/D[x+t]
		</formula>
		<formula name="f_A_xy_n_l_D" paras="f,x,y,n" fraction="6">
			1/(lx[x]*ly[y])*sum(1,n){v^{f+index-(1/2)}*((lx[x+f+index-1]+lx[x+f+index])/2)*d[y+f+index+1]}
		</formula>
	</Common>
</Benefit-formula>
