=== dtune/feeling/settings/formula/insurance/Formula-definition.dtd
<!ELEMENT BizExpenses ( formula+ ) >
<!ATTLIST BizExpenses desc CDATA #REQUIRED >

<!ELEMENT Common ( formula+ ) >
<!ATTLIST Common desc CDATA #REQUIRED >

<!ELEMENT Formula-definition ( BizExpenses, Common, Premium, ReserveFund, SurrenderFee ) >
<!ELEMENT common-formula ( Common ) >
<!ELEMENT Benefit-formula ( Common ) >
<!ELEMENT LifePension-formula ( Common ) >

<!ELEMENT Premium ( formula+ ) >
<!ATTLIST Premium desc CDATA #REQUIRED >

<!ELEMENT ReserveFund ( formula+ ) >
<!ATTLIST ReserveFund desc CDATA #REQUIRED >

<!ELEMENT SurrenderFee ( formula+ ) >
<!ATTLIST SurrenderFee desc CDATA #REQUIRED >

<!ELEMENT formula ( #PCDATA | formula )* >
<!ATTLIST formula accessable ( true | false ) #IMPLIED >
<!ATTLIST formula mate ( true | false ) #IMPLIED >
<!ATTLIST formula cacheable ( true | false ) #IMPLIED >
<!ATTLIST formula disaster ( true | false ) #IMPLIED >
<!ATTLIST formula desc CDATA #IMPLIED >
<!ATTLIST formula name CDATA #REQUIRED >
<!ATTLIST formula fundCode CDATA #IMPLIED >
<!ATTLIST formula pvh CDATA #IMPLIED >
<!ATTLIST formula limitedAge CDATA #IMPLIED >
<!ATTLIST formula limitedSex ( male | female ) #IMPLIED >
<!ATTLIST formula paras CDATA #IMPLIED >
<!ATTLIST formula value NMTOKEN #IMPLIED >
<!ATTLIST formula fraction CDATA #IMPLIED >
<!ATTLIST formula xtime ( 0 | 1 | 4 ) #IMPLIED >

=== dtune/feeling/settings/formula/insurance/265.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>

	<BizExpenses desc="事業費率の設定">
		<formula name="zeta">
			if(gen==2){0.030}else{0.025}
		</formula>
		<formula name="gamma" value="0.0007"/>
		<formula name="beta" value="0.10"/>
		<formula name="beta_nashu" value="0.070"/>
		<formula name="epsilon" value="0.003"/>
	</BizExpenses>
		
	<Common desc="商品内部の共通公式">	
		<!-- 生命年金現価  共通定義に移動する予定 -->
		<formula name="rou_xgo" paras="x">
			3/4*rhoxG[x]
		</formula>
		
		<formula name="q_xgo" paras="x">
			1/4*(3*qxG[x]+qx[x])
		</formula>
		
				<!-- 保険期間  -->
		<formula name="n_1" desc="保険期間(編集後)">
			if(n==99){
				omega-x+1
		    }else{n}
		</formula>
		<!-- 払込期間  -->
		<formula name="m_1" desc="払込期間(編集後)">
			if(m==99){
				omega-x+1
		    }else{m}
		</formula>
		
			<!--265専用生命年金現価　ここから -->
			<formula name="a_G_x_m" paras="x,m" fraction="5">
				(N[x]-N[x+m])/D[x]
			</formula>
			<formula name="S_a_G" paras="x,m" fraction="5">
				1+v*(1-q_xgo(x))*{(N[x+1]-N[x+m])/D[x+1]}
			</formula> 
			<formula name="a_TG_x_m" paras="x,m" fraction="5">
				if(kaiyakuUmu==0){
					(NTG[x]-NTG[x+m])/DTG[x]
				}else{
					(N[x]-N[x+m])/D[x]
				}
			</formula>
			<formula name="S_a_TG" paras="x,m" fraction="5">
				if(kaiyakuUmu==0){
					1+v*(1-q_xgo(x))*(1-qw)*
					{(NTG[x+1]-NTG[x+m])/DTG[x+1]}
				}else{
					1+v*(1-q_xgo(x))*(N[x+1]-N[x+m])/D[x+1]
				}
			</formula>
			<formula name="Sm_a_nashu_G" paras="m,x,n" fraction="5">
				if(kaiyakuUmu==0){
					if(n==m){
						0
					}else{
						v*(1-q_xgo(x))*(1-qw)*{DTG[x+m]/DTG[x+1]}*{(N[x+m]-N[x+n])/D[x+m]}
					}
				}else{
					if(n==m){
						0
					}else{
						v*(1-q_xgo(x))*(N[x+m]-N[x+n])/D[x+1]
					}
				}
			</formula>
			<formula name="mja_nashu_G" paras="m,j,x,n" fraction="5">
				if(kaiyakuUmu==0){
					if(n==m){
						0
					}elseIf(n&gt;m &amp;&amp; j&lt;m){
						DTG[x+m]/DTG[x+j]*{(N[x+m]-N[x+n])/D[x+m]}
					}elseIf(n&gt;m &amp;&amp; j==m){
						(N[x+m]-N[x+n])/D[x+j]
					}else{0}
				}else{
					if(n==m){
						0
					}else{
						(N[x+m]-N[x+n])/D[x+j]
					}
				}
			</formula>
			<formula name="a_TG12" paras="x,m" fraction="5">
				if(kaiyakuUmu==0){
					((NTG[x]-NTG[x+m])/DTG[x])-(11/24)*(1-DTG[x+m]/DTG[x])
				}else{
					(N[x]-N[x+m])/D[x]-11/24*(1-D[x+m]/D[x])
				}
			</formula>
			<formula name="S_a_TG12" paras="x,m" fraction="5">
				if(kaiyakuUmu==0){
					13/24+v*(1-q_xgo(x))*(1-qw)*((NTG[x+1]-NTG[x+m]+11/24*DTG[x+m])/DTG[x+1])
				}else{
					13/24+v*(1-q_xgo(x))*((N[x+1]-N[x+m]+(11/24)*D[x+m])/D[x+1])
				}
			</formula>
			
			<!--統計側依赖「統計側からの対応作業依頼.xls-」-->
			<formula name="S_a_k_TG" paras="k,x,m" fraction="5">
				if(kaiyakuUmu==0){
					(k+1)/(2*k)+v*(1-q_xgo(x))*(1-qw)*((NTG[x+1]-NTG[x+m]+(k-1)/(2*k)*DTG[x+m])/DTG[x+1])
				}else{
					(k+1)/(2*k)+v*(1-q_xgo(x))*((N[x+1]-N[x+m]+(k-1)/(2*k)*D[x+m])/D[x+1])
				}
			</formula>
					
			<!-- 給付現価　ここから -->
			<formula name="A_G_xj_nj" paras="x,j,n" fraction="6">
				(MS[x+j]-MS[x+n])/D[x+j]
			</formula>
			<formula name="SA_G" paras="x,n" fraction="6">
				v^(1/2)*rou_xgo(x)+v*(1-q_xgo(x))*{(MS[x+1]-MS[x+n])/D[x+1]}
			</formula>
			<formula name="SA_nashu_G" paras="x,n" fraction="6">
				if(kaiyakuUmu==0){
					v^(1/2)*rou_xgo(x)+v*(1-q_xgo(x))*(1-qw)
					*{(MT[x+1]-MT[x+m_1])/DTG[x+1]
					+DTG[x+m_1]/DTG[x+1]
					*{(MS[x+m_1]-MS[x+n])/D[x+m_1]}}
				}else{
					v^(1/2)*rou_xgo(x)+v*(1-q_xgo(x))*{(MS[x+1]-MS[x+n])/D[x+1]}
				}

			</formula>
			
			<formula name="A_nashu_G" paras="x,j,n" fraction="6">
				if(kaiyakuUmu==0){
					if(n==m_1){
						(MT[x+j]-MT[x+n])/DTG[x+j]
					}elseIf(n&gt;m_1 &amp;&amp; j&lt;m_1){
						(MT[x+j]-MT[x+m_1])/DTG[x+j]+DTG[x+m_1]/DTG[x+j]*(MS[x+m_1]-MS[x+n])/D[x+m_1]
					}elseIf(n&gt;m_1 &amp;&amp; j==m_1){
						(MS[x+j]-MS[x+n])/D[x+j]
					}else{0}
				}else{
					(MS[x+j]-MS[x+n])/D[x+j]
				}
			</formula>
		<!-- 下記の分割払いの係数定義は商品に問わずため、外部の共通commonフォルダに移す -->
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="5" desc="払込方法別Prate">
			<!-- 基準Prateと高額割引dより、払込方法別Prateを求める -->
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){0}
				elseIf(kaisu==2){12*d}
				elseIf(kaisu==3){6*d}
				else{d}
			</formula>
			stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d)
		</formula>
		
		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
				<!-- 普通の場合 -->
				if(kaisu==1){
					round(1/SBasePrate,4)
				}else{
					round(1/SBasePrate,2)
				}
		</formula>
	</Common>
	
	<Premium desc="保険料">
		
		<formula name="stdPrate" pvh="P" accessable="false" desc="基準Ｐレート">
			if(kaisu==1){singlePrate}else{MultiPrate}
			<formula name="singlePrate" fraction="5" desc="一時払いPrate">
				1/(1-beta_nashu)*(SA_G(x,n_1)+gamma*S_a_G(x,n_1))
			</formula>
			<formula name="MultiPrate" fraction="5" desc="分割払いPrate">
				(SA_nashu_G(x,n_1)+gamma*S_a_TG12(x,m_1)+gamma*Sm_a_nashu_G(m_1,x,n_1))
					/
				(12*(1-beta-zeta-epsilon)*S_a_TG12(x,m_1))
			</formula>
		</formula>
		
		<formula name="Prate" pvh="P" accessable="true" desc="１.保険料レート">
			PrateByPaymode(stdPrate,0)	
		</formula>
		
		<formula name="Premium" pvh="P" accessable="true" desc="２.保険料/保険金額">
<!--			 高額割引がゼロ 100円の位を切り上げ-->
			if(sptate==0){
<!--				 Ｐレートはゼロより小さい場合、ゼロとする -->
				roundDown(SA*max{PrateByPaymode(stdPrate,0),0},0)
			}else{
				roundUp(roundDown(SA*S2P(PrateByPaymode(stdPrate,0)),0)/1000,0)*1000
			}
		</formula>
	</Premium>
	
	<ReserveFund desc="責任準備金">
		<formula name="MultiV" fraction="4" paras="t">
			if(t==0){
					0
			}else{
				max(A_nashu_G(x,t,n_1)+gamma*mja_nashu_G(m_1,t,x,n_1)
					-
				(SA_nashu_G(x,n_1)+gamma*Sm_a_nashu_G(m_1,x,n_1))*a_TG_x_m(x+t,m_1-t)/S_a_TG(x,m_1),0)
			}
		</formula>
		<formula name="SingleV" fraction="4" paras="t">
			if(t==0){
				SA_G(x,n_1)+gamma*S_a_G(x,n_1)
			}else{
				A_G_xj_nj(x,t,n_1)+gamma*a_G_x_m(x+t,n_1-t)
			}
		</formula>
		
		<formula name="Vrate_accu" paras="t" desc="保険年度末rate">
			if(state==1||state==6){
				MultiV(t)
			}else{
				SingleV(t)
			}
		</formula>
		<formula name="Vrate" pvh="if(gen==2){V}else{H}" fraction="4" paras="t" desc="１.保険年度末Ｖレート">
			Vrate_accu(t)
		</formula>
		<formula name="ContractorYearV" pvh="P" paras="t" fraction="4" desc="保険年度契約者VTレート">
			Vrate_accu(t)
		</formula>
		<formula name="ContractorVrate" pvh="P" fraction="4" accessable="true" desc="３.契約者用Ｖレート">
			if(state==1||state==6){
				(1-f_12(f1))*ContractorYearV(t1)+f_12(f1)*ContractorYearV(t1+1)
			}elseIf(state==2||kaisu==1){
				(1-f_12(f))*ContractorYearV(t)+f_12(f)*ContractorYearV(t+1)
			}else{0}
		</formula>
		
		<formula name="BizYearV" paras="t" fraction="4" accessable="false" desc="事業末Vレート">
			if(state==1){			
			<!--保険料払込期間中-->			
				if(t==0){
					0
				}else{
					max(A_nashu_G(x,t,n_1)+gamma*mja_nashu_G(m_1,t,x,n_1)-((SA_nashu_G(x,n_1)+gamma*Sm_a_nashu_G(m_1,x,n_1))/S_a_TG(x,m_1))*a_TG_x_m(x+t,m_1-t),0)
				}
			}elseIf(state==2||state==6||kaisu==1){			
			<!-- 保険料払込期間終了後（一時払を含む) -->			
				if(t==0){
					SA_G(x,n_1)+gamma*S_a_G(x,n_1)
				}else{
					A_G_xj_nj(x,t,n_1)+gamma*a_G_x_m(x+t,n_1-t)
				}
			}else{0}
		</formula>

		<formula name="BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="２．事業年度末Vレート">
			BizYearV(t)
		</formula>
	</ReserveFund>

	<SurrenderFee desc="解約返戻金">
		<formula name="tSigma" paras="t" desc="tsigma">
				0.003*min(n_1/10,1)*max(1-t/min(m_1,10),0)
		</formula>
		<formula name="Vrate_V" pvh="V" paras="t">
			MultiV(t)
		</formula>
		<formula name="Wrate" fraction="4" pvh="P" accessable="true" desc="１.解約返戻金Ｗレート">
			if(PremiumAbolishSign==1){
				if(kaiyakuUmu==1){
				<!-- 解約返戻金あり -->
					if(state==1||state==6){
					<!-- 保険料払込期間中（保険料払込免除を含む）	 -->
						if(12*t1+f1&lt;12*t+f){
							(1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1)
						}else{
							(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
						}
					}elseIf(state==2||kaisu==1){
					<!-- 保険料払込期間終了後.一時払-->
						(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
					}else{0}
				}else{0}
			}elseIf(contractDate&gt;=20080202){
				if(kaiyakuUmu==1){
					if(state==1||state==6){
						v^ve*round((1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1),4)
					}elseIf(state==2||kaisu==1){
						(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
					}else{0}
				}else{0}
			}else{
				if(kaiyakuUmu==1){
					if(state==1||state==6){
						v^ve*round((1-f_12(f1))*min(tWrate(t1),Vrate_V(t1))
							+
						f_12(f1)*min(tWrate(t1+1),Vrate_V(t1+1)),4)
					}elseIf(state==2||kaisu==1){
						(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
					}else{0}
				}else{0}
			}
			
			<formula name="tWrate" paras="t" pvh="P" desc="解約返戻金Wレート">
				if(state==1||state==6){
					<!-- 払込期間中或は払込免除 -->
					if(t/min(m_1,10)&gt;=1){
						round(max(ContractorYearV(t),0),4)
					}else{
						round(max(ContractorYearV(t)-0.003*min(n_1/10,1)*(min(m_1,10)-t)/min(m_1,10),0),4)
					}
				}elseIf(state==2||kaisu==1){
					<!-- 払込期間終了後 -->
					max(ContractorYearV(t),0)
				}else{0}
			</formula>
		</formula>
	</SurrenderFee>
</Formula-definition>

=== dtune/feeling/settings/formula/special/030.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="x4Prate" xtime="4" desc="4倍体基準Prate">
			stdPrate
		</formula>
		<formula name="x1Prate" xtime="1" desc="1倍体基準Prate">
			stdPrate
		</formula>
		<formula name="Special_stdPrate" pvh="P" desc="特別条件付基準Prate">
			round((specialLambda-1)*(x4Prate-x1Prate)/(specialLambda1-1),4)
		</formula>
		<formula name="Special_Premium" pvh="P" accessable="true" desc="特別条件付保険料/保険金額">
			<!--Ｓ建てとして計算する -->
			roundDown(SA*max(PrateByPaymode(Special_stdPrate,0),0),0)
		</formula>
		
		<!--統計側依赖「統計側からの対応作業依頼.xls->NO.1,NO.2」-->
		<formula name="x4sts_stdPL" xtime="4" desc="統計側特体生存Pレート">
			PL
		</formula>
		<formula name="x4sts_stdPD" xtime="4" desc="統計側特体死亡Pレート">
			PD
		</formula>
		<formula name="x1sts_stdPL" xtime="1" desc="統計側標体生存Pレート">
			PL
		</formula>
		<formula name="x1sts_stdPD" xtime="1" desc="統計側標体死亡Pレート">
			PD
		</formula>
		<formula name="sts_stdPLSpecial" fraction="4" desc="統計側生存特体Prate">
			(specialLambda-1)/(specialLambda1-1)*(x4sts_stdPL-x1sts_stdPL)
		</formula>
		<formula name="sts_stdPDSpecial" fraction="4" desc="統計側死亡特体Prate">
			(specialLambda-1)/(specialLambda1-1)*(x4sts_stdPD-x1sts_stdPD)
		</formula>		
		<formula name="stsPLSpecial" pvh="P" desc="統計側生存特別条件付保険料">
			roundDown(SA*PrateByPaymode(sts_stdPLSpecial,0),0)
		</formula>
		<formula name="stsPDSpecial" pvh="P" desc="統計側死亡特別条件付保険料">
			roundDown(SA*PrateByPaymode(sts_stdPDSpecial,0),0)
		</formula>
	</Premium>

	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
		<formula name="x4ContractorVrate" xtime="4" desc="4倍体契約者用レート">
			ContractorVrate
		</formula>
		<formula name="x1ContractorVrate" xtime="1" desc="1倍体契約者用レート">
			ContractorVrate
		</formula>
		<formula name="Special_ContractorVrate" pvh="P" accessable="true" fraction="3" desc="特体契約者レート">
			(specialLambda-1)*(x4ContractorVrate-x1ContractorVrate)/(specialLambda1-1)
		</formula>
		<formula name="Special_Valuation" fraction="0" pvh="P" accessable="true" desc="特体契約者実額">
			max(SA*Special_ContractorVrate,0)
		</formula>
		
		<!-- 特体事業保険年度部分レート　ここから -->
		<formula name="Special_yearPrate" pvh="P" desc="年払Prate(PD+PL)">
			(x4Prate-x1Prate+stdPrate)*PayFactor(2,gen,1)-12*d
		</formula>
		
		<formula name="x4_PD" xtime="4" pvh="P" desc="特体死亡年払いPD">
			PD
		</formula>		
		<formula name="x4_PL" xtime="4" pvh="P" desc="特体年払生存PL">
			PL
		</formula>
		
		<formula name="x1_PD" pvh="P" xtime="1" desc="1倍体年払死亡PD">
			PD
		</formula>		
		<formula name="x1_PL" pvh="P" xtime="1" desc="1倍体年払生存PL">
			PL
		</formula>
		
		<formula name="nomalPD" pvh="P" xtime="0" desc="標準体年払死亡PD">
			PD
		</formula>
		<formula name="nomalPL" pvh="P" xtime="0" desc="標準体年払生存PL">
			PL
		</formula>
		
		
		<formula name="Special_yearPD" pvh="P" xtime="0" desc="年払いPD">
			(x4_PD-x1_PD+nomalPD)*PayFactor(2,gen,1)-12*d
		</formula>
		
		<formula name="Special_yearPL" pvh="P" desc="年払いPL">
			(x4_PL-x1_PL+nomalPL)*PayFactor(2,gen,1)
		</formula>	
		<formula name="Special_year_partV_D" paras="t" desc="事業保険年度部分Vrate死亡部分">
			if(compareBase &lt;= Special_yearPrate){
				(1+gamma2)*AT_xt_nt_D(x,n,t)+1W_xt_nt(x,n,t)+gamma1D*mt_a_nashu_xt_nm(t,n)
					-
				{(1+gamma2)*AT_x_n_D(x,n)+1W_x_n(x,n)+gamma1D*m_a_nashu_x_nm(n)}
				/aT_x_n(x,m)*aT_xt_nt(x,m,t)
			}else{
				(1+gamma2)*AT_xt_nt_D(x,n,t)+1W_xt_nt(x,n,t)+gamma1D*mj_a_nashu_xj_km(t,n)
				-Special_yearPD*aT_xt_nt(x,m,t)
			}
		</formula>
		<formula name="Special_year_partV_L" paras="t" desc="事業保険年度部分Vrate生存部分">
			if(compareBase &lt;= Special_yearPrate){
				I*{A_xt_nt_l(x,n,t)+gamma1L*mj_a_nashu_xj_km(t,n)
					-
				{A_x_n_l(x,n)+gamma1L*f_a_x_n(m,x,n)}/a_x_n(x,m)*a_x_n(x+t,m-t)}
			}else{
				I*{A_xt_nt_l(x,n,t)+gamma1L*mj_a_nashu_xj_km(t,n)}-Special_yearPL*a_x_n(x+t,m-t)
			}
		</formula>
		
		<formula name="Special_year_partV_DL" paras="t" fraction="3" desc="生存と死亡部分">
			Special_year_partV_D(t)+Special_year_partV_L(t)
		</formula>
		<formula name="x4BizYear" xtime="4" fraction="3" accessable="false" desc="4倍体事業年度末用Vレート">
			if(state==1){
				<!-- 保険料払込期間中 -->
				Special_year_partV_DL(t)
			}elseIf(state==2||state==6){
				<!-- 保険料払込終了後　或は払込免除 -->
				partPaidUpV_D(t)+partPaidUpV_L(t)
			}elseIf(state==3){
				<!-- 年金支払開始後 -->
				BenifitStartedV
			}else{
				0
			}
		</formula>
		<formula name="x1BizYear" xtime="1" fraction="3" accessable="false" desc="1倍体事業年度末用Vレート">
			BizYearV(t,0)
		</formula>
		<formula name="Special_BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="3" accessable="true" desc="特体業年度末Vレート">
			(specialLambda-1)*(x4BizYear-x1BizYear)/(specialLambda1-1)
		</formula>
		<formula name="Special_BizYearValuation" fraction="0" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="特体業年度末実額">
			SA*Special_BizYearVate
		</formula>
	</ReserveFund>
</Formula-definition>

=== dtune/feeling/settings/formula/insurance/225.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<BizExpenses desc="事業費率の設定">
		<formula name="AD_eta" value="0.00097" desc="予定先進医療発生率"/>
		<formula name="AD_tau" value="812846" desc="予定先進医療支払額"/>
		<formula name="AD_gamma" value="0.1" desc="維持費γ"/>
		<formula name="beta" value="0.15" desc="集金費β"/>
		<formula name="zeta" value="0.025" desc="集金費ζ"/>
		<formula name="epsilon" value="0.003" desc="Ｐ免費用ε"/>
		
	</BizExpenses>
	<Common desc="商品内部の共通公式">
		<formula name="q1" paras="x">
			qx[x]+qw-qx[x]*qw
		</formula>
		<formula name="vq" paras="x">
			1-v*(1-q1(x))
		</formula>
		<formula name="vqe" paras="x,n">
			{v*(1-q1(x))}^n
		</formula>
		<formula name="aT_x_n" paras="x,n" fraction="5">
			(1-vqe(x,n))/vq(x)
		</formula>
		<formula name="aT12_x_n" paras="x,n" fraction="5">
			(1-vqe(x,n))/vq(x)-11/24*(1-vqe(x,n))
		</formula>
		<formula name="ad_A_x_n" paras="x,n">
			v^(1/2)*AD_eta*AD_tau*aT_x_n(x,n)
		</formula>
			
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="0"
			desc="払込方法別Prate">
			<!-- 基準Prateと高額割引dより、払込方法別Prateを求める -->
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){
					0
				}elseIf(kaisu==2){
					12*d
				}elseIf(kaisu==3){
					6*d
				}else{
					d
				}
			</formula>
			round(stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d),0-1)
		</formula>

		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
			round(1/SBasePrate,2)
		</formula>
	</Common>

	<Premium desc="保険料">		
		<formula name="stdPrate" pvh="P" accessable="false" fraction="0" desc="基準Ｐレート">
			ad_A_x_n(40,n)/{12*(1-AD_gamma-beta-zeta-epsilon)*aT12_x_n(40,n)}
		</formula>
		
		<formula name="Prate" pvh="P" accessable="true" desc="１.保険料レート">
			PrateByPaymode(stdPrate,0)
		</formula>		
		<formula name="Premium" pvh="P" accessable="true" desc="２.保険料/保険金額">
			if(sptate==0){
				Prate
			}else{
			   roundUp(roundDown(SA*S2P(PrateByPaymode(stdPrate,0)),0)/1000,0)*1000
			}
			
		</formula>
	</Premium>
	
	<ReserveFund desc="保険積立金">
		<formula name="MultiV" paras="t" desc="払込中VTレート">
			0
		</formula>
		<formula name="WaiverV" paras="t" fraction="0" desc="払込免除のVTレート">
			ad_A_x_n(40,n-t)+AD_gamma*ad_A_x_n(40,n)*aT_x_n(40,n-t)/((1-AD_gamma-beta-zeta-epsilon)*aT_x_n(40,n))
		</formula>
		<formula name="Vrate_accu" paras="t" desc="保険年度Vrate">
			if(state==1){
				<!-- 払込期間中 -->
				MultiV(t)
			}elseIf(state==6){
				<!-- 払込免除 -->
				WaiverV(t)
			}else{
				0
			}		
		</formula>
		<formula name="Vrate" pvh="H" accessable="true" desc="１.保険年度末Ｖレート">
			Vrate_accu(t)
		</formula>
		
		<formula name="BizYearV" paras="t" fraction="0" desc="事業末Vレート">
			Vrate_accu(t)
		</formula>
		
		<formula name="BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="２．事業年度末Vレート">
			BizYearV(t)
		</formula>
		
		<formula name="ContractorYearV" fraction="0" pvh="P" paras="t" desc="保険年度契約者VTレート">
			Vrate_accu(t)
		</formula>

		<formula name="ContractorVrate" fraction="0" pvh="P" accessable="true" desc="３．契約者用Ｖレート">
			if(state==1){
				<!-- 払込期間中 -->
				0
			}elseIf(state==6){
				<!-- 払込免除 -->
				if (f==0){
					<!-- 保険年度末Ｖレート -->
					ContractorYearV(t)
				}else{
					<!-- 契約者用Ｖレート -->
					(1-(2*f-1)/24)*ContractorYearV(t)+((2*f-1)/24)*ContractorYearV(t+1)
				}
			}else{
				0
			}
		</formula>
		<formula name="VrateValuation" pvh="H" fraction="0" accessable="true" desc="４．保険年度末V実額">
			Vrate
		</formula>
		<formula name="Valuation" pvh="P" fraction="0" accessable="true" desc="５．契約者責任準備金実額">
			ContractorVrate
		</formula>
		<formula name="BizYearValuation" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="0" accessable="true" desc="６．事業年度末V実額">
			BizYearVate
		</formula>

	</ReserveFund>

	<SurrenderFee desc="解約返戻金">
		<formula name="tWrate">
			0
		</formula>
		<formula name="Wrate" pvh="P" accessable="true" desc="１.解約返戻金Ｗレート">
			0
		</formula>
	</SurrenderFee>
</Formula-definition>

=== dtune/feeling/settings/formula/insurance/003.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<BizExpenses desc="事業費率の設定">
		<formula name="alpha">
			roundDown(0.017+0.008*min(n/10,1),8)
		</formula>
		<formula name="delta">
			if(kaisu==1){
				0
			}else{
				roundDown(0.02*min(max(min(m,10),2*m-20)/20,1),8)
			}
 		</formula>
		<formula name="gamma">
			if(gen==1){0.00215}else{0.00205}
		</formula>
		<formula name="gamma_nashu" value="0.002"/>
		<formula name="gamma1" value="0.001"/>
		<formula name="gamma2" value="0.001"/>
		<formula name="beta" value="0.03"/>
		<formula name="zeta">
			if(gen==1){0.04}
			elseIf(gen==2){0.03}
			else(0.025)
		</formula>
		<formula name="epsilon">
			if(m&lt;=5){
				0.0005
			}elseIf(m&gt;5&amp;&amp;m&lt;=10){
				0.001
			}else{
				0.002
			}
		</formula>
	</BizExpenses>
	
	<Common desc="商品内部の共通公式">
		<!-- 高額割引率 -->
		<formula name="d" desc="高額割引率">
			if(xtime&gt;0){
				0
			}else{
				if(gen==3||gen==4){
			    	if(SA&lt;10000000){
			    		0
			    	}elseIf(SA&gt;=10000000&amp;&amp;SA&lt;30000000){
			    		0.00002
			    	}else{
			    		0.00003
			    	}  
				}else{
					if(SA&lt;10000000){
						0
					}else{
						0.00002
					}
				}
			}
		</formula>
		<!-- これからは共通公式 -->
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="6" desc="払込方法別Prate">
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){0}
				elseIf(kaisu==2){12*d}
				elseIf(kaisu==3){6*d}
				else{d}
			</formula>
			stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d)
		</formula>
		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
				<!-- 普通の場合 -->
				if(kaisu==1){
					round(1/SBasePrate,4)
				}else{
					round(1/SBasePrate,2)
				}
		</formula>
	</Common>
	
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="stdPrate" pvh="P" desc="基準Pレート">
			if(kaisu==1){singlePrate}else{MultiPrate}
			<formula name="singlePrate" fraction="5" desc="一時払いPレート">
				A_x_n(x,n)+alpha+gamma_nashu*a_x_n(x,n)
			</formula>
			<formula name="MultiPrate" fraction="6" desc="分割払いPレート">
				{A_x_n(x,n)+alpha+gamma*a_k_x_n(12,x,m)+gamma_nashu*f_a_x_n(m,x,n)}
					/
				{12*(1-beta-zeta-delta-epsilon)*a_k_x_n(12,x,m)}
					+
				0.000000000001
			</formula>
		</formula>
		<formula name="Prate" pvh="P" accessable="true" desc="１．保険料レート">
			PrateByPaymode(stdPrate,d)	
		</formula>
		<formula name="PrateByYear" pvh="P" fraction="6" desc="年払Prate">
			stdPrate*PayFactor(2,gen,1)-12*d
		</formula>
		<!-- OL用計算公式 -->
		<formula name="SA_d" paras="d,SA_PrateUnit">
			roundUp(roundDown(SA_PrateUnit*S2P(PrateByPaymode(stdPrate,d)),0)/1000,0)*1000
		</formula>
		<formula name="SA_Premium" paras="SA_PrateUnit">
			if(gen==3||gen==4){
				if(SA_d(0.00003,SA_PrateUnit)&gt;=30000000){
					SA_d(0.00003,SA_PrateUnit)
				}elseIf(SA_d(0.00002,SA_PrateUnit)&gt;=10000000 &amp;&amp; SA_d(0.00002,SA_PrateUnit)&lt;30000000){
					SA_d(0.00002,SA_PrateUnit)
				}else{
					SA_d(0,SA_PrateUnit)
				}
			}else{
				if(SA_d(0.00002,SA_PrateUnit)&gt;10000000){
					SA_d(0.00002,SA_PrateUnit)
				}else{
					SA_d(0,SA_PrateUnit)
				}
			}
		</formula>
		<formula name="Premium" pvh="P" paras="stdPrate" accessable="true" desc="２．保険料・保険金">
			if(sptate==0){
				roundDown(SA*max{PrateByPaymode(stdPrate,d),0},0)
			}else{
				SA_Premium(SA)
			}
		</formula>
	</Premium>
	
	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
	    <formula name="live" paras="t,tEX" fraction="4" desc="契約日からの保険期間nEXに端月数がない場合生存部分">
			A_xt_nt_l(x,tEX,t)+gamma2*a_x_n(x+t,tEX-t)
		</formula>
		<formula name="dead_sub1" paras="t,tEX" fraction="4" desc="契約日からの保険期間nEXに端月数がない場合死亡部分">
	    	A_xt_nt_D(x,t,tEX)+gamma1*a_x_n(x+t,tEX-t)
	    </formula>
		<formula name="dead" paras="t,tEX,fEX" fraction="4" desc="契約日からの保険期間nEXに端月数がある場合死亡部分">
			if(t&lt;tEX){
				(1-fEX/12)*dead_sub1(t,tEX)+fEX/12*dead_sub1(t,tEX+1)
			}elseIf(t==tEX){
				fEX/12*dead_sub1(t,tEX+1)
			}else{0}
		</formula>

		<!-- 保険年度末保険料積立金レート(期間中) -->
		<formula name="Vrate_endofYear_kkc" paras="t,z" desc="保険年度末保険料積立金レート(期間中)">
			max{
				A_x_n(x+t,n-t)+gamma_nashu*a_x_n(x+t,n-t)
					-
				(A_x_n(x,n)+gamma_nashu*a_x_n(x,n))/a_x_n(x,m)*a_x_n(x+t,m-t)
					-
				if(z==0){0}else{alpha/a_x_n(x,z)*a_x_n(x+t,z-t)}
			,0}
		</formula>
		<!-- 保険年度末保険料積立金レート(期間終了) -->
		<formula name="Vrate_endofYear_kksl" paras="t" desc="保険年度末保険料積立金レート(期間終了)">
        	A_x_n(x+t,n-t)+gamma_nashu*a_x_n(x+t,n-t)
		</formula>
		
		<formula name="Vrate_accu" paras="t,z" desc="保険年度末rate">
			if(kaisu==1||state==2||state==4){
				<!-- 一時払 保険料払込期間終了(払済保険を含む) -->
				Vrate_endofYear_kksl(t)
			}elseIf(state==1||state==6){
				<!-- 保険料払込期間中(保険料払込免除を含む)-->
                Vrate_endofYear_kkc(t,z)
			}elseIf{state==7}{
				<!-- 延長定期保険 -->	
				if(SAS!=0){
					live(t,tEX)
				}else{
					dead(t,tEX,fEX)
				}
			}else{0}
		</formula>
		<!-- 保険年度末保険料積立金レート(sub) -->		
		<formula name="Vrate" fraction="4" pvh="H" accessable="true" desc="１．保険年度末Vレート">
			Vrate_accu(t,0)
		</formula>
		<!-- 契約者用Vレート -->
		<formula name="ContractorYearV" paras="t,z" fraction="4" pvh="P" accessable="false" desc="契約者用Vレート">
			Vrate_accu(t,z)
		</formula>
		
		<formula name="ContractorVrate" pvh="P" fraction="4" accessable="true" desc="３．契約者用Vレート">
			if(kaisu==1||state==2||state==4||state==7){
				(1-f_12(f))*ContractorYearV(t,z)+f_12(f)*ContractorYearV(t+1,z)
			}elseIf(state==1||state==6){
				(1-f_12(f1))*ContractorYearV(t1,z)+f_12(f1)*ContractorYearV(t1+1,z)
			}else{
				0
			}
		</formula>
		
		<formula name="BizYearV" paras="t,z" accessable="false" desc="事業年度末Vレート">
			if(kaisu==1){
				<!-- 一時払 -->
				Vrate_endofYear_kksl(t)
			}else{
				if(state==1){
					<!-- 保険料払込期間中 -->
			  		if(round((A_x_n(x,n)+gamma_nashu*f_a_x_n(m,x,n))/a_x_n(x,m),6)&lt;PrateByYear){
			  			Vrate_endofYear_kkc(t,z)
			  		}else{
			 		 	max{
			 		 		A_x_n(x+t,n-t)+gamma_nashu*a_x_n(x+t,n-t)-(PrateByYear+gamma_nashu)
			 		 		*a_x_n(x+t,m-t)-if(z==0){0}else{alpha/a_x_n(x,z)*a_x_n(x+t,z-t)}
			 		 	,0}
			  		}
			    }elseIf(state==2||state==6||state==4){
					<!-- 保険料払込期間終了後（払済保険を含む）,保険料払込免除契約-->
					Vrate_endofYear_kksl(t)
				}elseIf(state==7){
					<!-- 延長定期保険-->
					if(SAS!=0){
			  			live(t,tEX)
			  		}else{
			  			dead(t,tEX,fEX)
			  		}
			  	}else{0}
			}
		</formula>
		
		<formula name="calBizYearV" fraction="4" desc="事業末用Vレート">
			BizYearV(t,z)
		</formula>
		
	</ReserveFund>
	
	<!-- 解約返戻金　ここから -->
	<SurrenderFee desc="解約返戻金">
		<formula name="tWrate" paras="t" pvh="P">
			<formula name="sigma" paras="t">
				(0.013+0.006*min(n/10,1))*max(1-t/min(m,10),0)
			</formula>
			if(kaisu==1||state==2||state==4){
				<!-- 一時払　-->
				max{ContractorYearV(t,0),0}
			}elseIf(state==1||state==6){
		      	<!--払込期間中　または　免除 -->
			  	round(max{ContractorYearV(t,0)-sigma(t),0),4)
			}elseIf(state==7){
				<!-- 延長定期保険 -->
				if(SAS!=0){
					max{live(t,tEX),0}
				}else{
					max{dead(t,tEX,fEX),0}
				}
			}else{0}
		</formula>
		<formula name="Wrate" fraction="4" pvh="P" accessable="true" desc="１．解約返戻金Wレート">
			<formula name="Wrate_Sub1" paras="t,z">
				min{tWrate(t),Wrate_Sub5(t,z)}
				<formula name="Wrate_Sub5" pvh="V" paras="t,z" fraction="4" >
					Vrate_endofYear_kkc(t,z)
				</formula>
			</formula>
			if(kaisu==1||state==2||state==4){
				((1-f_12(f)))*tWrate(t)+f_12(f)*tWrate(t+1)
			}elseIf(state==1||state==6){
			  	if(PremiumAbolishSign==1){
					if((12*t1+f1-12*t-f)&lt;0){
           				((1-f_12(f1)))*tWrate(t1)+f_12(f1)*tWrate(t1+1)
           			}else{
           				((1-f_12(f)))*tWrate(t)+f_12(f)*tWrate(t+1)
           			}
			  	}elseIf(contractDate&gt;=20080202){
			    	v^ve*round((1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1),4)
			  	}else{
			    	v^ve*round((1-f_12(f1))*Wrate_Sub1(t1,min(m,5))+f_12(f1)*Wrate_Sub1(t1+1,min(m,5)),4)
			  	}
			}elseIf(state==7){
			    if(SAS!=0){
			    	(1-f_12(f))*live(t,tEX)+f_12(f)*live(t+1,tEX)
			  	}else{
			  		(1-f_12(f))*dead(t,tEX,fEX)+f_12(f)*dead(t+1,tEX,fEX)
			  	}
			}else{0}
		</formula>
	</SurrenderFee>	
</Formula-definition>
