=== dtune/feeling/settings/formula/insurance/Formula-definition.dtd
<!ELEMENT BizExpenses ( formula+ ) >
<!ATTLIST BizExpenses desc CDATA #REQUIRED >

<!ELEMENT Common ( formula+ ) >
<!ATTLIST Common desc CDATA #REQUIRED >

<!ELEMENT Formula-definition ( BizExpenses, Common, Premium, ReserveFund, SurrenderFee ) >
<!ELEMENT common-formula ( Common ) >
<!ELEMENT Benefit-formula ( Common ) >
<!ELEMENT LifePension-formula ( Common ) >

<!ELEMENT Premium ( formula+ ) >
<!ATTLIST Premium desc CDATA #REQUIRED >

<!ELEMENT ReserveFund ( formula+ ) >
<!ATTLIST ReserveFund desc CDATA #REQUIRED >

<!ELEMENT SurrenderFee ( formula+ ) >
<!ATTLIST SurrenderFee desc CDATA #REQUIRED >

<!ELEMENT formula ( #PCDATA | formula )* >
<!ATTLIST formula accessable ( true | false ) #IMPLIED >
<!ATTLIST formula mate ( true | false ) #IMPLIED >
<!ATTLIST formula cacheable ( true | false ) #IMPLIED >
<!ATTLIST formula disaster ( true | false ) #IMPLIED >
<!ATTLIST formula desc CDATA #IMPLIED >
<!ATTLIST formula name CDATA #REQUIRED >
<!ATTLIST formula fundCode CDATA #IMPLIED >
<!ATTLIST formula pvh CDATA #IMPLIED >
<!ATTLIST formula limitedAge CDATA #IMPLIED >
<!ATTLIST formula limitedSex ( male | female ) #IMPLIED >
<!ATTLIST formula paras CDATA #IMPLIED >
<!ATTLIST formula value NMTOKEN #IMPLIED >
<!ATTLIST formula fraction CDATA #IMPLIED >
<!ATTLIST formula xtime ( 0 | 1 | 4 ) #IMPLIED >

=== dtune/feeling/settings/formula/special/205.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="specialPrate" xtime="4" desc="4倍体基準Prate">
			P_self
		</formula>
		<formula name="normalPrate" xtime="1" desc="1倍体基準Prate">
			P_self
		</formula>
		<formula name="Special_stdPrate" fraction="3" desc="特別条件付基準Prate">
			(specialLambda-1)*(specialPrate-normalPrate)/(specialLambda1-1)+0.000000000001
		</formula>
		<formula name="Special_Prate" pvh="P" desc="特別条件付Prate">
			PrateByPaymode(Special_stdPrate,0)
		</formula>
		<formula name="Special_Premium" pvh="P" accessable="true" desc="特別条件付保険料/保険金額">
			<!--Ｓ建てとして計算する -->
			roundDown(SA*max(PrateByPaymode(Special_stdPrate,0),0),0)
		</formula>
	</Premium>

	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
		<formula name="x4ContractorVrate" xtime="4" desc="4倍体契約者用レート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			ContractorVrate
		</formula>
		
		<formula name="x1ContractorVrate" xtime="1" desc="1倍体契約者用レート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			ContractorVrate
		</formula>
		<formula name="Special_ContractorVrate" pvh="P" accessable="true" paras="t" fraction="2" desc="特体契約者レート">
			(specialLambda-1)*(x4ContractorVrate-x1ContractorVrate)/(specialLambda1-1)
		</formula>
		<formula name="Special_Valuation" fraction="0" pvh="P" accessable="true" desc="特体契約者実額">
			max(SA*Special_ContractorVrate,0)
		</formula>
		<formula name="x4BizYear" xtime="4" fraction="2" accessable="false" desc="4倍体事業年度末用Vレート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			BizYearV(t)
		</formula>
		<formula name="x1BizYear" xtime="1" fraction="2" accessable="false" desc="1倍体事業年度末用Vレート">
			<!--配偶者、子部分は0-->
			set{contractorType=1}
			BizYearV(t)
		</formula>
		<formula name="Special_BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="2" accessable="true" desc="特体事業年度末レート">
			(specialLambda-1)*(x4BizYear-x1BizYear)/(specialLambda1-1)
		</formula>
		<formula name="Special_BizYearValuation" fraction="0" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="特体業年度末実額">
			SA*Special_BizYearVate
		</formula>
	</ReserveFund>
</Formula-definition>

=== dtune/feeling/settings/formula/insurance/309.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
	<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<BizExpenses desc="事業費率の設定">
		<!-- 予定事業費率 -->
		<formula name="alpha" paras="n" desc="新契約費(alpha)">
			roundDown(0.006*min(n/10,1),8)
		</formula>
		<formula name="delta" paras="n" fraction="3" desc="新契約費(delta)">
			if(kaisu==1){
				max{0.04-0.01/5*max(x+n-55,0),0}
			}else{
				max{0.06-0.01/5*max(x+n-55,0),0}
			}
	    </formula>
		<formula name="gamma" desc="維持費（払込中)(gamma)">
			if(gen==1){0.00115}
			elseIf(gen==5)(0.00126)
			else{0.00105}
		</formula>
		<formula name="gamma1" value="0.001" desc="維持費（払込終了、一時払を含む)(gamma1)" />
		<formula name="beta" value="0.03" desc="集金費beta" />
		<formula name="zeta" desc="集金費zeta">
			if(gen==1){0.04}
			elseIf(gen==2){0.03}
			else{0.025}
		</formula>
		<formula name="epsilon" paras="m" desc="保険料払込免除(epsilon)">
		       if(m&lt;=5){0.0005}
		       elseIf(m&gt;5 &amp;&amp; m&lt;=10){0.0010}
		       else{0.0020}
		</formula>
	</BizExpenses>
	
	<Common desc="商品内部の共通公式">
		<!-- これからは共通公式 -->
		<formula name="qDD" paras="x,ptn" desc="予定死亡率">
			if(gen==5){
				if(contractUpdType==1 || ptn==1){
					qxDD1[x]
				}else{
					1/4*(3*qxDD1[x]+qxDD2[x])
				}
			}else{
				1/4*(3*qxDD1[x]+qxDD2[x])
			}
		</formula>
				
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="6" desc="払込方法別Prate">
			<!-- 基準Prateと高額割引dより、払込方法別Prateを求める -->
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){0}
				elseIf(kaisu==2){12*d}
				elseIf(kaisu==3){6*d}
				else{d}
			</formula>
			stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d)
		</formula>

		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
			<!-- 普通の場合 -->
			if(kaisu==1){
			    round(1/SBasePrate,4)
			}else{
			   round(1/SBasePrate,2)
			}
		</formula>

		<!-- 309専用生命年金現価　ここから -->
		
		<formula name="aDD_x_m" paras="x,m" fraction="5">
			if(m&lt;=0){
				0
			}else{
				(N[x]-N[x+m])/D[x]
			}
		</formula>
		
		<formula name="Sa_DD" paras="x,m,ptn" fraction="5">
			1+v*(1-qDD(x,ptn))*aDD_x_m(x+1,m-1)
		</formula>
				
		<formula name="Sa12" paras="x,m,ptn" fraction="5">
			13/24+v*(1-qDD(x,ptn))*(11/24+A12(x+1,m-1))
			<formula name="A12" paras="x,m" fraction="5">
				(N[x]-N[x+m])/D[x]-(11/24)*(1-D[x+m]/D[x])
			</formula>
		</formula>
		
		<formula name="ma_DD" paras="m,x,n" fraction="5">
			(N[x+m]-N[x+n])/D[x]
		</formula>
		
		<formula name="S_m_aDD_x_nm" paras="m,x,n,ptn" fraction="5">
			v*(1-qDD(x,ptn))*ma_DD(m-1,x+1,n-1)
		</formula>
		
		
		<!-- 給付現価　ここから -->
		<formula name="S_A1_DD" paras="x,n,ptn" fraction="6" >
			v^(1/2)*qDD(x,ptn)+v*(1-qDD(x,ptn))*A1_DD(x+1,n-1)
			<formula name="A1_DD" paras="x,n" fraction="6">
				1/D[x]*sum(0,n-1){C[x+index]}
			</formula>
		</formula>	
	</Common>
	<Premium desc="保険料">
		<formula name="stdPrate" pvh="P" desc="基準Ｐレート">
			if(kaisu==1){singlePrate}else{MultiPrate(1)}
			<formula name="singlePrate" fraction="5" desc="一時払いPレート">
				{S_A1_DD(x,n,0)+alpha(n)+gamma1*Sa_DD(x,n,0)}/(1-delta(n))
			</formula>
			<formula name="MultiPrate" paras="ptn" fraction="6" desc="分割払いPレート">
				if(m==n){
					if((x+n)&lt;90){
						set(t_Prate=MultiPrateCompare(n,ptn))
						set(i=n)
						while(i&lt;90-x){
							t_Prate=min(t_Prate,MultiPrateCompare(i,ptn))
							set(i=i+1)
						}						
					}else{
						MultiPrateCompare(n,ptn)
					}
				}elseIf(m&lt;n){
					MultiPrate2(ptn)
				}else{0}
				<formula name="MultiPrateCompare" paras="n,ptn">
					{S_A1_DD(x,n,ptn)+alpha(n)+gamma*Sa12(x,n,ptn)}/jyosu(n,n,ptn)
				</formula>
				<formula name="MultiPrate2" paras="ptn">
					{S_A1_DD(x,n,ptn)+alpha(n)+gamma*Sa12(x,m,ptn)+gamma1*S_m_aDD_x_nm(m,x,n,ptn)}/jyosu(n,m,ptn)
				</formula>
				<formula name="jyosu" paras="n,m,ptn">
					12*(1-beta-zeta-delta(n)-epsilon(m))*Sa12(x,m,ptn)
				</formula>
			</formula>
		</formula>
		<formula name="Prate" pvh="P" accessable="true" desc="１．保険料レート">
			PrateByPaymode(stdPrate,0)
		</formula>	
		<formula name="adjustStdPrate" desc="調整基準Ｐレート">
			if(gen==5){
				if(kaisu==1){0}
				else{PrateByPaymode(MultiPrate(1),0)-PrateByPaymode(MultiPrate(0),0)}
			}else{0}
		</formula>
		
		<formula name="adjustPrate" pvh="P" desc="調整P実額">
			if(contractUpdType==1){
				<!-- 更新契約 -->
				0
			}else{
				<!-- 新契約 -->
				round(SA*adjustStdPrate,0)
			}
		</formula>
		
		<!-- OL用計算公式 -->
		<formula name="Premium" pvh="P" paras="stdPrate" accessable="true"
			desc="２．保険料・保険金">
			if(sptate==0){
				roundDown(SA*max{PrateByPaymode(stdPrate,0),0},0)
			}else{
				roundUp(
					roundDown(
						SA*S2P(PrateByPaymode(stdPrate,0))
					,0)/1000
				,0)*1000
			}
		</formula>
	</Premium>

	<ReserveFund desc="責任準備金">
		<!--a.保険年度末保険料積立金 -->
		<formula name="Vrate_accu" paras="t,z">
			<formula name="alpha_z">
				0.008*min(n/10,1)
			</formula>
			max(
			if(state==1||state==6){
			<!--保険料払込期間中・保険料払込免除後  -->
			if(gen==5){
					if(t==0){
						0
					}else{
						A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)-(S_A1_DD(x,n,0)+gamma1*Sa_DD(x,n,0))/Sa_DD(x,m,0)*aDD_x_m(x+t,m-t)
							-
						if(z==0){0}else{alpha_z/Sa_DD(x,z,0)*aDD_x_m(x+t,z-t)}
					}
				}else{
					if(t==0){
						0
					}else{
						max(A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)-(S_A1_DD(x,n,0)+gamma1*Sa_DD(x,n,0))/Sa_DD(x,m,0)*aDD_x_m(x+t,m-t)
							-
						if(z==0){0}else{alpha_z/Sa_DD(x,z,0)*aDD_x_m(x+t,z-t)}
						,0)
					}
				}
			}elseIf(state=2||kaisu==1){
			<!-- 保険料払込期間終了後・一時払 -->
				if(t==0){
					S_A1_DD(x+t,n-t,0)+gamma1*Sa_DD(x+t,n-t,0)
				}else{
					A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)
				}
			}else{0}
			,0)
		</formula>

		<formula name="Vrate" paras="t" pvh="H" fraction="4" accessable="true" desc="１．保険年度末Vレート">
			Vrate_accu(t,0)
		</formula>

		<formula name="ContractorYearV" paras="t,z" pvh="P" fraction="4" desc="契約者用Vレート">
			Vrate_accu(t,z)
		</formula>

		<formula name="ContractorVrate" fraction="4"  pvh="P" accessable="true" desc="３．契約者用Vレート">
			if(state==1||state==6){
				(1-f_12(f1))*ContractorYearV(t1,z)+f_12(f1)*ContractorYearV(t1+1,z)
			}elseIf(state=2||kaisu==1){
				(1-f_12(f))*ContractorYearV(t,z)+f_12(f)*ContractorYearV(t+1,z)
			}else{
				0
			}
		</formula>
		
		<formula name="yearPrate" pvh="P" fraction="6" desc="年払Ｐrate">
			stdPrate*PayFactor(2,gen,1)
		</formula>
		
		<formula name="BizYearV" paras="t,z" accessable="false" desc="事業末Vレート">
			max(
			if(state==1){
			<!-- 保険料払込期間中 -->
				if(gen==5){
					if(t==0){
						0
					}else{
						if(round((S_A1_DD(x,n,0)+gamma1*S_m_aDD_x_nm(m,x,n,0))/Sa_DD(x,m,0),6)&lt;=yearPrate){
							Vrate_accu(t,z)
						}else{
							A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)-(yearPrate+gamma1)*aDD_x_m(x+t,m-t)
								-
							if(z==0){0}else{(0.008*min(n/10,1))/Sa_DD(x,z,0)*aDD_x_m(x+t,z-t)}
						}
					}
				}else{
					if(t==0){
						0
					}else{
						if((S_A1_DD(x,n,0)+gamma1*S_m_aDD_x_nm(m,x,n,0))/Sa_DD(x,m,0)&lt;=yearPrate){
							Vrate_accu(t,z)
						}else{
							A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)-(yearPrate+gamma1)*aDD_x_m(x+t,m-t)
								-
							if(z==0){0}else{(0.008*min(n/10,1))/Sa_DD(x,z,0)*aDD_x_m(x+t,z-t)}
						}
					}
				}
			}elseIf(state==2||state==6||kaisu==1){
			<!-- 保険料払込期間終了後・保険料払込免除後・一時払 -->
				if(t==0){
					S_A1_DD(x+t,n-t,0)+gamma1*Sa_DD(x+t,n-t,0)
				}else{
					A1_DD(x+t,n-t)+gamma1*aDD_x_m(x+t,n-t)
				}
			}else{0}
			,0)
		</formula>			
		<formula name="calBizYearV" fraction="4" desc="事業末用Vレート">
			BizYearV(t,z)
		</formula>
	</ReserveFund>
		
	<SurrenderFee desc="解約返戻金">
			
		<formula name="tWrate" paras="t" pvh="P" desc="解約返戻金Wレート">
			<formula name="tSigma" paras="t">
				0.006*min(n/10,1)*max{1-(t/min(m,10)),0}
			</formula>
			if(state==2||kaisu==1){
				<!-- 払込期間終了後 -->
				max(ContractorYearV(t,0),0)
			}elseIf(state==1||state==6){
				<!-- 払込期間中或は払込免除 -->
				round(max(ContractorYearV(t,0)-tSigma(t),0),4)
			}else{0}
		</formula>
		<formula name="VrateVbaseZ" paras="t,z" pvh="V" fraction="4" desc="保年末V（V基礎）">
			Vrate_accu(t,z)
		</formula>
		<formula name="Wrate" pvh="P" fraction="4" accessable="true" desc="１．解約返戻金Wレート">
			if(PremiumAbolishSign==1){
				if(state==2||kaisu==1){
					(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
				}elseIf(state==1||state==6){
					if(12*t1+f1&lt;12*t+f){
						(1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1)
					}else{
						((1-f_12(f)))*tWrate(t)+f_12(f)*tWrate(t+1)
					}
				}else{0}
			}elseIf(contractDate&gt;=20080202){
				if(state==2||kaisu==1){
					(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
				}elseIf(state==1||state==6){
					v^ve*round((1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1),4)
				}else{0}
			}else{
				if(state==2||kaisu==1){
					(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
				}elseIf(state==1||state==6){
					v^ve*round((1-f_12(f1))*min(tWrate(t1),VrateVbaseZ(t1,min(m,5)))+f_12(f1)*min(tWrate(t1+1),VrateVbaseZ(t1+1,min(m,5))),4)
				}else{0}
			}
		</formula>
	</SurrenderFee>
</Formula-definition>

=== dtune/feeling/settings/formula/insurance/014.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<BizExpenses desc="事業費率の設定">
		<!-- 予定事業費率 -->	
		<formula name="c" value="1" desc="逓増周期c"/>
		<formula name="k" value="5" desc="上限率k"/>
		<formula name="Sj" paras="j" desc="第ｊ保険年度の死亡保険金率Sj">
			if(teizoKbn==0){
				min(1+theta*((j-1)/c),k)
			}else{
				min((1+theta)^((j-1)/c),k)
			}
		</formula>
		<formula name="alpha" desc="新契約費α">
			round{0.006*min(n/10,1)*nj_Sj(1,n)/n,8}
		</formula>
		<formula name="delta" desc="新契約費δ">
			if(kaisu==1){
				round{max(0.04-(0.01/5)*max(x+n-55,0),0),3}
			}else{
				round{max(0.06-(0.01/5)*max(x+n-55,0),0),3}
			}
		</formula>
		<formula name="gamma" desc="維持費（払込中）γ">
			if(gen==1){
				round{0.00115*nj_Sj(1,m)/m,8}
			}else{
				round{0.00105*nj_Sj(1,m)/m,8}
			}
		</formula>
		<formula name="gamma_nashu" desc="維持費（払込終了）γ'">
			if(n==m){
				0
			}else{
				round{0.001*nj_Sj(m+1,n)/(n-m),8}
			}
		</formula>
		<formula name="gamma1" desc="維持費（一時払）γ1">
			round{0.001*nj_Sj(1,n)/n,8}
		</formula>
		<formula name="gamma2" value="0.001" desc="維持費（払済保険）γ2"/>
		<formula name="beta" value="0.03" desc="集金費β"/>
		<formula name="zeta" desc="集金費ζ">
			if(gen==1){0.04}elseIf(gen==2){0.03}else{0.025}
		</formula>
		<formula name="epsilon" desc="保険料払込免除ε">
			if(m&lt;=5){
				0.0005
			}elseIf(m&gt;5 &amp;&amp; m&lt;=10){
				0.001
			}else{
				0.002
			}
		</formula>
		<formula name="theta" desc="逓増率θ">
			if(teizoKbn==0){0.1}else{0.05}
		</formula>
		<formula name="hkin1">
			roundDown{roundDown{(20000000*n/nj_Sj(1,n)),0}/1000000,0}*1000000
		</formula>
		<formula name="hkin2">
			roundDown{roundDown{(30000000*n/nj_Sj(1,n)),0}/1000000,0}*1000000
		</formula>
		<formula name="hkin3">
			roundDown{roundDown{(50000000*n/nj_Sj(1,n)),0}/1000000,0}*1000000
		</formula>
		<formula name="d" desc="高額割引率d">
			if(xtime&gt;0){
				0
			}else{
				if(SA&lt;hkin1){
					0
				}elseIf(SA&gt;=hkin1 &amp;&amp; SA&lt;hkin2){
					if(gen==3 || gen==4){
						round{0.00002*nj_Sj(1,n)/n,6}
					}else{0}
				}elseIf(SA&gt;=hkin2 &amp;&amp; SA&lt;hkin3){
					if(gen==3 || gen==4){
						round{0.00002*nj_Sj(1,n)/n,6}
					}elseIf(gen==2){
						round{0.000015*nj_Sj(1,n)/n,6}
					}else{
						round{0.00001*nj_Sj(1,n)/n,6}
					}
				}else{
					if(gen==3 || gen==4){
						round{0.00004*nj_Sj(1,n)/n,6}
					}elseIf(gen==2){
						round{0.00003*nj_Sj(1,n)/n,6}
					}else{
						round{0.00001*nj_Sj(1,n)/n,6}
					}
				}
			}
		</formula>
	</BizExpenses>
	
	<Common desc="商品内部の共通公式">
		<formula name="nj_Sj" paras="sn,n">
			sum(sn,n){Sj(index)}
		</formula>
		<!-- 共通定義、ここから -->
		<formula name="a_k_x_n" paras="x,n" fraction="5" desc="始期払k回年金現価">
			(N[x]-N[x+n])/D[x]-(11/24)*(1-D[x+n]/D[x])	
		</formula>
		<formula name="C1" paras="x">
			C[x]
		</formula>
		
		<!-- 下記の分割払いの係数定義は商品に問わずため、外部の共通commonフォルダに移す -->
		<formula name="S2P" paras="SBasePrate" desc="S基準からP基準に変換する">
			if(kaisu==1){
				round(1/SBasePrate,4)
			}else{
				round(1/SBasePrate,2)
			}
		</formula>		
		<formula name="SjC1">
			sum(1,n){Sj(index)*C1(x+index-1)}
		</formula>
		
		<formula name="PrateByPaymode" paras="stdPrate,d" fraction="6" desc="保険料レート">
			<!-- 基準Prateと高額割引dより、払込方法別Prateを求める -->
			<formula name="Discount" paras="d" desc="高額割引">
				if(kaisu==1){0}
				elseIf(kaisu==2){12*d}
				elseIf(kaisu==3){6*d}
				else{d}
			</formula>
			stdPrate*PayFactor(kaisu,gen,keiro)-Discount(d)
		</formula>

	</Common>
	
	<Premium desc="保険料">
		<formula name="SingleP" fraction="5" desc="一時払Pレート">
			((1/D[x])*SjC1+alpha+gamma1*a_x_n(x,n))/(1-delta)
		</formula>
		<formula name="MultiP" fraction="6" desc="分割払Pレート">
			((1/D[x])*SjC1+alpha+gamma*a_k_x_n(x,m)+gamma_nashu*f_a_x_n(m,x,n))
					/
			(12*(1-beta-zeta-delta-epsilon)*a_k_x_n(x,m))
		</formula>		
		<formula name="stdPrate" pvh="P" desc="基準Ｐレート">
			if(kaisu==1){<!--　ここから、 一時払い開始 -->
				SingleP
			}else{<!--　ここから、 分割払い開始 -->
				MultiP
			}
		</formula>
		<formula name="PrateByYear" fraction="6" desc="年払Prate">
			stdPrate*PayFactor(2,gen,1)-12*d
		</formula>
		
		<formula name="Prate" accessable="true" pvh="P" desc="１．保険料レート">
			PrateByPaymode(stdPrate,d)
		</formula>
		
		<formula name="Premium" pvh="P" accessable="true" desc="２．保険料・保険金">
			if(x+n-1&gt;128){
				0
			}else{
				<!-- 高額割引がゼロ 100円の位を切り上げ-->
				if(sptate==0){
					<!-- Ｐレートはゼロより小さい場合、ゼロとする -->
					roundDown(SA*max{PrateByPaymode(stdPrate,d),0},0)
				}else{
					roundUp(roundDown(SA*S2P(PrateByPaymode(stdPrate,d)),0)/1000,0)*1000
				}
			}
		</formula>
	</Premium>
	<ReserveFund desc="保険積立金">
		<!-- 保険年度末保険料積立金 -->
		<formula name="SingleV" paras="t" desc="一時払VTレート">
			(1/D[x+t])*sum(t+1,n){Sj(index)*C1(x+index-1)}+gamma1*a_x_n(x+t,n-t)
		</formula>
		<formula name="MultiV" paras="t,z" desc="払込中（免除）VTレート">
			set(alphaz=(0.008*min(n/10,1)*nj_Sj(1,n))/n)
			max{
				{(1/D[x+t])*sum(t+1,n){Sj(index)*C1(x+index-1)}+gamma_nashu*a_x_n(x+t,n-t)}
				-
				((1/D[x])*sum(1,n){Sj(index)*C1(x+index-1)}+gamma_nashu*a_x_n(x,n))*a_x_n(x+t,m-t)/a_x_n(x,m)
				-
				if(z==0){0}else{(alphaz/a_x_n(x,z))*a_x_n(x+t,z-t)}
			,0}
		</formula>
		<formula name="PaidupV" paras="t" desc="払済保険VTレート">
			A_xt_nt_D(x,t,n)+gamma2*a_x_n(x+t,n-t)
		</formula>
		<formula name="PaymentEndV" paras="t" desc="払込期間終了後のVTレート">
			(1/D[x+t])*sum(t+1,n){Sj(index)*C1(x+index-1)}+gamma_nashu*a_x_n(x+t,n-t)		
		</formula>
		
		<formula name="Vrate_accu" paras="t,z" desc="保険年度末rate">
			if(kaisu==1){
				SingleV(t)
			}elseIf(state==4){
				PaidupV(t)
			}elseIf(state==1 || state==6){
				MultiV(t,z)
			}elseIf(state==2){
				PaymentEndV(t)
			}else{0}
		</formula>
		<formula name="Vrate" pvh="H" fraction="4" accessable="true" desc="１．保険年度末Vレート">
			Vrate_accu(t,0)
		</formula>

		<!-- 契約者保険年度Vrate　ここから -->
		<formula name="ContractorYearV" paras="t,z" pvh="P" fraction="4" desc="契約者保険年度Vrate">
			Vrate_accu(t,z)
		</formula>	
			
		<!-- 契約者保険年度Vrate(保険料払込年数または経過年数が整数でない場合)　ここから -->
		<formula name="ContractorVrate" pvh="P" accessable="true" fraction="4" desc="３．契約者用Vレート">
			if(state==4||state==2||kaisu==1){
				<!-- 払済 -->
				(1-f_12(f))*ContractorYearV(t,z)+(f_12(f))*ContractorYearV(t+1,z)
			}elseIf(state==1 || state==6){
				<!-- 払込期間中まだは免除 -->
				(1-f_12(f1))*ContractorYearV(t1,z)+(f_12(f1))*ContractorYearV(t1+1,z)
			}else(0)
		</formula>
		
		<formula name="Vrate_Overbar1">
			{(1/D[x])*sum(1,n){Sj(index)*C1(x+index-1)}+gamma_nashu*ft_a_xt_n(m,0,x,n)}/a_x_n(x,m)
		</formula>
		
		<formula name="BizYearV" paras="t,z" accessable="false" desc="事業末Vレート">
			if(kaisu&gt;1){	
				if(state==4){
					<!-- 払済 -->
					PaidupV(t)
				}elseIf(state==1){
					if(round(Vrate_Overbar1,6)&lt;=PrateByYear){
						MultiV(t,z)
					}else{
						<!-- 払込期間中-->	
						set(alphaz=0.008*min(n/10,1)*nj_Sj(1,n)/n)
						max{
							
							{(1/D[x+t])*sum(t+1,n){Sj(index)*C1(x+index-1)}+gamma_nashu*a_x_n(x+t,n-t)}
							-
							(PrateByYear+gamma_nashu)*a_x_n(x+t,m-t)
							-
							if(z==0){0}else{(alphaz/a_x_n(x,z))*a_x_n(x+t,z-t)}
						,0}
					}
				}elseIf(state==2||state==6){
					<!-- 払込期間終了後 .免除-->
					PaymentEndV(t)
				}else(0)
			}elseIf(kaisu==1){
				<!-- 一時払 -->
				SingleV(t)
			}else{0}
		</formula>
		
		<formula name="calBizYearV" fraction="4" desc="事業末用Vレート">
			BizYearV(t,z)
		</formula>

	</ReserveFund>
	
	<!-- 解約返戻金　ここから -->
	<SurrenderFee desc="解約返戻金">
		<formula name="tWrate" paras="t" pvh="P" fraction="4">
			<formula name="sigma" paras="t">
				0.006*min(n/10,1)*(nj_Sj(1,n)/n)*max{1-t/min(m,10),0}
			</formula>
			max{
				if(state==4||kaisu==1||state==2){
					<!-- 払済 -->
					ContractorYearV(t,0)
				}elseIf(state==1 || state==6){
					<!-- 払込期間中まだは免除 -->
					ContractorYearV(t,0)-sigma(t)
				}else{0}
			,0}
		</formula>
		<formula name="Wrate" fraction="4" pvh="P" accessable="true" desc="１．解約返戻金Wレート">
			<formula name="Wrate_Overbar1">
				if(12*t1+f1-12*t-f&lt;0){
					<!-- 払込年月数-経過年月数<0の場合、t,fをt1,f1に読み替え -->
					(1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1)
				}else{
					(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
				}				
			</formula>
			<formula name="Wrate_Overbar2">
				v^ve*round((1-f_12(f1))*tWrate(t1)+f_12(f1)*tWrate(t1+1),4)
			</formula>
			<formula name="MultiV_V" fraction="4" pvh="V" paras="t">
				MultiV(t,min(m,5))
			</formula>
			<formula name="Wrate_Overbar3">
				v^ve*round((1-f_12(f1))*min{tWrate(t1),MultiV_V(t1)}+f_12(f1)*min{tWrate(t1+1),MultiV_V(t1+1)},4)
			</formula>
			<formula name="Wrate_Overbar4">
				(1-f_12(f))*tWrate(t)+f_12(f)*tWrate(t+1)
			</formula>
			if(state==4||kaisu==1||state==2){
				<!-- 払済 -->
				Wrate_Overbar4
			}elseIf(state==1 || state==6){
				<!-- 払込期間中まだは免除 -->
				if(PremiumAbolishSign==1){
					Wrate_Overbar1
				}elseIf(contractDate&gt;=20080202){
					Wrate_Overbar2
				}else{
					Wrate_Overbar3
				}
			}else(0)
		</formula>
	</SurrenderFee>
</Formula-definition>

=== dtune/feeling/settings/formula/special/304.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Formula-definition SYSTEM "Formula-definition.dtd">
<!-- 商品毎に計算公式はここに定義する -->
<Formula-definition>
	<!-- 保険料　ここから -->
	<Premium desc="保険料">
		<formula name="x4Prate" xtime="4" desc="4倍体基準Prate">
			stdPrate
		</formula>
		<formula name="x1Prate" xtime="1" desc="1倍体基準Prate">
			stdPrate
		</formula>
		<formula name="Special_stdPrate" desc="特別条件付基準Prate">
			if(kaisu==1){
				round((specialLambda-1)*(x4Prate-x1Prate)/(specialLambda1-1)+0.000000000001,5)
			}else{
				round((specialLambda-1)*(x4Prate-x1Prate)/(specialLambda1-1)+0.000000000001,6)
			}
		</formula>
		<formula name="Special_Prate" pvh="P" desc="特別条件付Prate">
			PrateByPaymode(Special_stdPrate,0)
		</formula>
		<formula name="Special_Premium" pvh="P" accessable="true" desc="特別条件付保険料/保険金額">
			<!--Ｓ建てとして計算する -->
			roundDown(SA*max(PrateByPaymode(Special_stdPrate,0),0),0)
		</formula>
	</Premium>

	<!-- 責任準備金　ここから -->
	<ReserveFund desc="責任準備金">
		<formula name="normalPrate" pvh="P" xtime="0" fraction="6" desc="標準体Prate">
			PayFactor(2,gen,1)*stdPrate-12*d
		</formula>
		<formula name="Special_PrateByYear" pvh="P" fraction="6" desc="特体用年払Prate">
	        round((x4Prate-x1Prate)*PayFactor(2,gen,1),6)+normalPrate
	    </formula>
		
		<formula name="x4ContractorVrate" xtime="4" desc="4倍体契約者用レート">
			ContractorVrate
		</formula>
		
		<formula name="x1ContractorVrate" xtime="1" desc="1倍体契約者用レート">
			ContractorVrate
		</formula>

		<formula name="Special_ContractorVrate" pvh="P" accessable="true" fraction="4" desc="特体契約者レート">
			(specialLambda-1)*(x4ContractorVrate-x1ContractorVrate)/(specialLambda1-1)
		</formula>
		<formula name="Special_Valuation" fraction="0" pvh="P" accessable="true" desc="特体契約者実額">
			max(SA*Special_ContractorVrate,0)
		</formula>
		
		<formula name="Vratebiz_Sub2" desc="事業年度末用保険年度末Vレート(SUB2)">
			round((Kiyoutu_Sub1+gamma_nashu*f_a_x_n(m,x,n))/a_x_n(x,m),6)
		</formula>
		<formula name="x4BizYear" xtime="4" fraction="4" accessable="false" desc="4倍体事業年度末用Vレート">
			if(state==1){
				if(Vratebiz_Sub2&lt;=Special_PrateByYear){
					Vrate_Sub2(t,0)
				}else{
					max{
					Kiyoutu_Sub2(t)+gamma_nashu*a_x_n(x+t,n-t)
					-(Special_PrateByYear+gamma_nashu)*a_x_n(x+t,m-t)
					,0}				
				}
			}else{
			BizYearV(t,0)
			}
		</formula>
		<formula name="x1BizYear" xtime="1" fraction="4" accessable="false" desc="1倍体事業年度末用Vレート">
			BizYearV(t,0)
		</formula>
		<formula name="Special_BizYearVate" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" fraction="4" accessable="true" desc="特体事業年度末レート">
			(specialLambda-1)*(x4BizYear-x1BizYear)/(specialLambda1-1)
		</formula>
		<formula name="Special_BizYearValuation" fraction="4" pvh="if(kisoritsu==0){P}elseIf(kisoritsu==1){V}else{H}" accessable="true" desc="特体業年度末実額">
			SA*Special_BizYearVate
		</formula>
	</ReserveFund>
</Formula-definition>
